### ISSUE TITLE
建议换成OKHttp，google官方已经在4.4 和4.4 + 的网络请求中公开支持OKHttp了，未来会是主流，不是所有的android开发都喜欢用async-http

### ISSUE THREAD

**Issue by xiaomeixw** [qiniu/android-sdk#134]
RT....本身自己APP就有网络请求的架构，现在为使用千牛又要增加一个新jar包。建议换成OKHttp，还有请把happy-dns源代码copy到代码中(随着对方版本的升级而替换源代码)，最终只生产一个jar包..好不好--这样不是更方便开发者~~

**Comment by longbai** [comment]
1 我知道okhttp 从性能和使用上全面胜出，我们这边javasdk 就是用的okhttp。但sdk优先考虑兼容性，有的时候宁肯辛苦点，选择不好用但兼容性好的API。 如果您实在要用okhttp, 可以直接基于java sdk来编写项目。或者将 httpmanager里面的实现更换一下，这个地方已经进行了封装，方便将来的调整。
2 happy-dns 和 上传sdk 解决不同方面的问题，有不同的开发进度，所以不方便放在一起。
3 async http 我最看重的一点是代码比较小，您就把android sdk看作黑盒，不用去管其中的内容吧。

**Comment by xiaomeixw** [comment]
@longbai 嗯，好的，明白了....谢谢了....
