### ISSUE TITLE
public void progress(String key, double percent) 不是在主线程的

### ISSUE THREAD

**Issue by wy315700** [qiniu/android-sdk#136]
public void progress(String key, double percent) 不是在主线程的
public void progress(String key, double percent) 不是在主线程的
public void progress(String key, double percent) 不是在主线程的
重要的事情说三遍

**Comment by longbai** [comment]
我看下

**Comment by liujing906qd** [comment]
同样的问题

**Comment by liujing906qd** [comment]
但是complete是OK的

**Comment by longbai** [comment]
之前查了代码 都是同样的调用发起者，奇怪，我再仔细看下。

**Comment by longbai** [comment]
fixed #147
