### ISSUE TITLE
loopj 1.4.9 remove apache jar

### ISSUE THREAD

**Issue by Haoxiqiang** [qiniu/android-sdk#138]
Warning: com.qiniu.android.http.HttpManager: can't find referenced method 'void setRedirectHandler(org.apache.http.client.RedirectHandler)' in program class com.qiniu.android.http.AsyncHttpClientMod
Warning: com.qiniu.android.http.HttpManager: can't find referenced method 'com.loopj.android.http.RequestHandle post(android.content.Context,java.lang.String,org.apache.http.Header[],org.apache.http.HttpEntity,java.lang.String,com.loopj.android.http.ResponseHandlerInterface)' in program class com.qiniu.android.http.AsyncHttpClientMod
Warning: com.qiniu.android.http.HttpManager$2: can't find referenced method 'com.loopj.android.http.RequestHandle post(android.content.Context,java.lang.String,org.apache.http.Header[],org.apache.http.HttpEntity,java.lang.String,com.loopj.android.http.ResponseHandlerInterface)' in program class com.qiniu.android.http.AsyncHttpClientMod
Warning: there were 3 unresolved references to program class members.

A terrible problem!

**Comment by longbai** [comment]
是的，我这边 准备重新写一下

**Comment by Haoxiqiang** [comment]
我也是刚看到,我提一个pullrequest吧
