### ISSUE TITLE
什么时候加同步上传方式

### ISSUE THREAD

**Issue by zeng1990java** [qiniu/android-sdk#140]
什么时候加同步上传方式，什么时候加同步上传方式，什么时候加同步上传方式。现在只有异步方式上传。

**Comment by longbai** [comment]
您好，android这边一般都是异步方式，如果实在要求同步方式 可以1 使用java sdk，接口相近，可以同步上传 2 把目前的sdk进行下封装，加上同步锁 就可以同步上传了。
