### ISSUE TITLE
和 multidex 一起使用会有问题

### ISSUE THREAD

**Issue by KynoYang** [qiniu/android-sdk#149]
Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: com/loopj/android/http/AsyncHttpClient$1.class

最新的 7.0.9 版本。

**Comment by longbai** [comment]
这个是不是把同样的 com/loopj/android/http/AsyncHttpClient 包 打包了两遍造成的？

**Comment by KynoYang** [comment]
是。
查了下，其他地方也库也用到了 AsyncHttpClient。

也可能是 multidex 的 bug 吧。
