### ISSUE TITLE
上传图片的时候会在进度95%的时候卡十几二十秒的时间

### ISSUE THREAD

**Issue by WanghongLin** [qiniu/android-sdk#150]
由0到95%的过程是正常的，但是到了95%后就会一直卡着，十多二十秒之后才会上传完成。
我这里使用的是版本是

compile 'com.qiniu:qiniu-android-sdk:7.0.9

**Comment by longbai** [comment]
这个可能是本地网络比较慢，sdk这里 到95 有个判断，要等到所有上传完毕，并且服务器响应之后 才能到100%

**Comment by matianchi** [comment]
这种情况经常出现，无论是wifi还是4G，且相同网络环境下，ios并无卡在95，希望彻底查明原因。

**Comment by longbai** [comment]
麻烦提供下 android sdk版本 以及 机型信息

**Comment by WanghongLin** [comment]
com.qiniu:qiniu-android-sdk:7.0.9
多款机型都有，Nexus 5，Sony xperia，小米

**Comment by longbai** [comment]
https://github.com/qiniudemo/qiniu-lab-android 这个是 我们的demo，平时测试没这个问题，能麻烦再给下 图片大小信息么？另外最好通过工单把账号提供给我们，我们的同事可以在后台查下日志

**Comment by matianchi** [comment]
已经将帐号提交到工单，工单编号5351。
图片为300K左右。
图片链接地址：http://7xn0ps.com2.z0.glb.qiniucdn.com/f82a8d38-7957-44fc-b600-9105f0bb07c3-6c0430dfc475340ec4b0328515601d19

**Comment by WanghongLin** [comment]
demo这里运行不起来。另外demo的配置比较旧。还是api 19的。有没有可能是兼容性的问题，我这里是compileSdkVersion 23
targetSdkVersion 23
没有org.apache.http模块的

**Comment by netdxy** [comment]
已电话沟通反馈已解决
