### ISSUE TITLE
建议在readme增加sdk混淆配置

### ISSUE THREAD

**Issue by dongorigin** [qiniu/android-sdk#151]

**Comment by longbai** [comment]
收到，我们看下

**Comment by longbai** [comment]
如果没有特别需求的话，com.qiniu 包下面建议都不用混淆

**Comment by dongorigin** [comment]
收到，建议在文档中提一下这个问题

**Comment by netdxy** [comment]
您好，七牛的SDK本身就是开源的，不需要对七牛的SDK需要做特殊混淆处理，所以在混淆的时候将七牛相关的包都排除就可以了。 
1. 在Android Studio中，混淆配置在 proguard-rules.pro 里面加上下面几行混淆代码就可以了：
-keep class com.qiniu.**{*;}
-keep class com.qiniu.**{public <init>();}
-ignorewarnings

注意：-ignorewarnings这个也是必须加的，如果不加这个编译的时候可能是可以通过的，但是release的时候还是会出现错误。 
2. 对于Eeclipse中也是一样的，在proguard-project.txt 文件附件同样的排除代码就可以了
-keep class com.qiniu.**{*;}
-keep class com.qiniu.**{public <init>();}
-ignorewarnings

**Comment by dongorigin** [comment]
明白了，感谢

**Comment by longbai** [comment]
多谢建议，已经加上
