### ISSUE TITLE
android-async-http导致带端口的url无法访问

### ISSUE THREAD

**Issue by jjz** [qiniu/android-sdk#152]
https://github.com/loopj/android-async-http/issues/1000
建议使用1.4.7版本

**Comment by longbai** [comment]
囧，多谢提醒，不过 我这边单元测试是通过的啊

**Comment by jjz** [comment]
我这边试用的时候带端口号就不可以，所以我把你们的sdk降到7.0.7就可以了

**Comment by longbai** [comment]
建议 使用 7.0.7.x 系列，一些bugfix 已经合并过来。另外也可以用 7.1 系列，更换到了 okhttp

**Comment by lvke88** [comment]
您好，想问下，为什么必须使用80和443端口，而且不指定端口，网络请求就超时

**Comment by longbai** [comment]
@lvke88 能麻烦给下详细的日志和测试场景么
