### ISSUE TITLE
UploadManager 的post方法是支持在非ui线程调用的吗？

### ISSUE THREAD

**Issue by mralong** [qiniu/android-sdk#154]
hello,我在com.qiniu.android.storage.UploadManager类的源码里面看到这样的一段代码，
 public void put(File file, final String key, String token, final UpCompletionHandler completionHandler,
                    final UploadOptions options) {
        if (areInvalidArg(key, null, file, token, completionHandler)) {
            return;
        }
        UpToken decodedToken = UpToken.parse(token);
        if (decodedToken == null) {
            final ResponseInfo info = ResponseInfo.invalidToken("invalid token");
            AsyncRun.run(new Runnable() {
                @Override
                public void run() {
                    completionHandler.complete(key, info, null);
                }
            });
            return;
        }
        long size = file.length();
        if (size <= config.putThreshold) {
            FormUploader.upload(httpManager, config, file, key, decodedToken, completionHandler, options);
            return;
        }
        String recorderKey = config.keyGen.gen(key, file);
        ResumeUploader uploader = new ResumeUploader(httpManager, config, file, key,
                decodedToken, completionHandler, options, recorderKey);

        AsyncRun.run(uploader);
    }

在这个代码里面，如果是文件大小小与配置的文件大小，则使用表单上传，否则使用分片上传，但是在这里的分片上传是使用了AsyncRun，然后在ui线程跑，然后表单上传却是直接调用。
不知道我的理解有没有错，如果没有错的话，这个是基于什么样的考量呢？

**Comment by longbai** [comment]
哦，这个 真实上传 还是在另外的线程，这个asyncrun是让当前的调用快速结束
