### ISSUE TITLE
UpCompletionHandler 成功的回调是否可以提供上传成功后图片的url地址返回?

### ISSUE THREAD

**Issue by xiaomeixw** [qiniu/android-sdk#156]
JSONObject only return hash & key ,could return image url?

**Comment by longbai** [comment]
不行的，因为url 需要域名，上传不需要

**Comment by xiaomeixw** [comment]
@longbai 是为了安全考虑吗?因为我这边只看到返回成功，但不知道实际是否成功，所以想知道最终上传成功的图片，在浏览器中可以访问的URL地址。

**Comment by longbai** [comment]
@xiaomeixw 不好意思，不是为了安全考虑，上传这边没有域名概念，只有bucket，一个bucket可以绑定多个域名。 下载的url 可以用bucket里的域名+key 拼接就成
