### ISSUE TITLE
提供直接提交的方法，返回固定json格式，开发者自己解析

### ISSUE THREAD

**Issue by water54** [qiniu/android-sdk#160]
不知道你们考虑过普通的一个上传流程是怎样的没有？先从自己服务器上获取token，然后切换到主线程调用你们的api，再通过回调又切到主线程拿到结果，然后再开线程把key上传到自己的服务器，获取完整URL。整个流程本来只是一件事，完全可以封装到一个线程里。而因为你们的设计完全打破了。代码凌乱不堪。还要另加一个网络库....同时，一次提交根本无法提交多个文件，如果遇到需要上传多张图片的场景，这场景太美，我都不敢想象~希望能够直接提供一个上传api。解释清楚入参，出参。

**Comment by water54** [comment]
我甚至可以接受用你们的调用方法，但必须是线程同步的方法，同时支持多文件同时长传的，这点都做不到恐怕真的不敢推荐

**Comment by longbai** [comment]
1 流程和线程是两回事。想要同步也行，用个semaphore。
2 token的来源 我们不假定。
3 上传可以不用主线程调用，只是回调在主线程而已。
4 一次提交多个文件，需要如何保证多个文件同时成功的事务原子性？
5 如果需要特别定制化的需求，建议参考token放置header的方法 自己写就可以了。
