### ISSUE TITLE
AndroidStuidio 打包 引入七牛sdk的项目 失败

### ISSUE THREAD

**Issue by larryonline** [qiniu/android-sdk#161]
打包Release版本时出现下面的警告导致打包失败

Warning:com.qiniu.android.http.HttpManager$3: can't find referenced method 'com.qiniu.android.http.IReport access$100(com.qiniu.android.http.HttpManager)' in program class com.qiniu.android.http.HttpManager

**Comment by longbai** [comment]
请问 有做代码混淆吗？

**Comment by blusewang** [comment]
混淆后加入官方的配置了。也是这样
`-keep class com.qiniu.**{*;}
-keep class com.qiniu.**{public <init>();}
-keep class com.squareup.**{*;}
-keep class okio.**{*;}
-ignorewarnings`

**Comment by longbai** [comment]
这个有点奇怪，sdk版本给下，android sdk版本也给下

**Comment by blusewang** [comment]
build.gradle
apply plugin: 'com.android.application'

android {
    signingConfigs {
        config {
            keyAlias 'xxx'
            keyPassword 'xxx'
            storeFile file('/Users/bluse/mobile/xxx.jks')
            storePassword 'xxx'
        }
    }
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    defaultConfig {
        applicationId "com.xxx.wgj"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        signingConfig signingConfigs.config
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.config
        }
        debug {
            minifyEnabled true
            signingConfig signingConfigs.config
        }
    }
    productFlavors {
    }
    useLibrary 'org.apache.http.legacy'
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile project(':scanqr')
    compile files('libs/libammsdk.jar')
    compile 'com.loopj.android:android-async-http:1.4.8'
    compile 'com.yancy.imageselector:imageselector:1.3.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile files('libs/TencentLocationSDK_v4.4.6_r206631_151119_1441.jar')
    compile files('libs/TencentMapSDK_Raster_v1.1.2.16281.jar')
    compile 'com.qiniu:qiniu-android-sdk:7.1.+'
    compile 'com.qiniu:qiniu-java-sdk:7.0.+'
}

proguard-rules.pro
-keep class com.tencent.mm.sdk.** {*;}
-libraryjars libs/TencentMapSDK_*_vx.x.x.x.jar
-keep class com.tencent.mapsdk.**{*;}
-keep class com.tencent.tencentmap.**{*;}
-keep class com.qiniu.**{*;}
-keep class com.qiniu.**{public ();}
-keep class com.qiniu.android.http.**{*;}

-keep class com.squareup.**{*;}
-keep class okio.**{*;}





如果还有什么需要，随时联系我。微信/tel： 15311217906




在 2016-02-22 03:41:56，"Bai Long" <notifications@github.com> 写道：


这个有点奇怪，sdk版本给下，android sdk版本也给下
