### ISSUE TITLE
手机断网后上传文件不会返回失败，会无限重试

### ISSUE THREAD

**Issue by YaleZheng** [qiniu/android-sdk#162]
重现步骤:
1.通过UploadManager上传文件
2.断开网络
3.UpCompletionHandler永远没有回调

**Comment by YaleZheng** [comment]
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err: java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:499)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:468)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:182)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at java.net.DatagramSocket.send(DatagramSocket.java:281)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at com.qiniu.android.dns.local.Resolver.udpCommunicate(Resolver.java:50)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at com.qiniu.android.dns.local.Resolver.resolve(Resolver.java:34)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at com.qiniu.android.dns.DnsManager.queryInternal(DnsManager.java:132)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at com.qiniu.android.dns.DnsManager.query(DnsManager.java:82)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at com.qiniu.android.http.ClientConnectionOperator.systemResolv(ClientConnectionOperator.java:243)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at com.qiniu.android.http.ClientConnectionOperator.openConnection(ClientConnectionOperator.java:141)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
12-17 11:11:05.911 12247-13591/com.goldmf.GMFund W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
12-17 11:11:05.921 12247-13591/com.goldmf.GMFund W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
12-17 11:11:05.921 12247-13591/com.goldmf.GMFund W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-17 11:11:05.921 12247-13591/com.goldmf.GMFund W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-17 11:11:05.921 12247-13591/com.goldmf.GMFund W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-17 11:11:05.921 12247-13591/com.goldmf.GMFund W/System.err:     at java.lang.Thread.run(Thread.java:841)
12-17 11:11:05.921 12247-13591/com.goldmf.GMFund W/System.err: Caused by: libcore.io.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
12-17 11:11:05.921 12247-13591/com.goldmf.GMFund W/System.err:     at libcore.io.Posix.sendtoBytes(Native Method)
12-17 11:11:05.921 12247-13591/com.goldmf.GMFund W/System.err:     at libcore.io.Posix.sendto(Posix.java:156)
12-17 11:11:05.921 12247-13591/com.goldmf.GMFund W/System.err:     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
12-17 11:11:05.921 12247-13591/com.goldmf.GMFund W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:466)
12-17 11:11:05.921 12247-13591/com.goldmf.GMFund W/System.err: 	... 22 more

**Comment by longbai** [comment]
多谢，我们这边看下

**Comment by jemygraw** [comment]
目前没有这种情况，关闭。
