### ISSUE TITLE
如何修改上传文件的文件名

### ISSUE THREAD

**Issue by f630088281** [qiniu/android-sdk#163]
如题，怎么修改上传文件的文件名啊。。。

**Comment by f630088281** [comment]
fname怎么使用  for android

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by f630088281** [comment]
大哥  我比较紧急。。。

**Comment by Chirstopher** [comment]
hi，安卓上传里面，key才是上传文件后的文件名

UploadManager uploadManager = new UploadManager();
data = <File对象、或 文件路径、或 字节数组>
String key = <指定七牛服务上的文件名，或 null>;
String token = <从服务端SDK获取>;
uploadManager.put(data, key, token,
new UpCompletionHandler() {
    @Override
    public void complete(String key, ResponseInfo info, JSONObject res) {
        //  res 包含hash、key等信息，具体字段取决于上传策略的设置。 
        Log.i("qiniu", key + ",\r\n " + info + ",\r\n " + res);
    }
}, null);

看String key才是文件名

**Comment by f630088281** [comment]
不好意思啊   先前卡了   同一条消息点了这么多。。。。                                                                            为何我上传的 都是filename ="" 或 filename="filename"
小小实习生  求大神指教

**Comment by f630088281** [comment]
{"filename":"filename","id":9185,"url":"http:\/\/78rc7c.com1.z0.glb.clouddn.com\/documents\/9f12a1d556d749ddaf5ad775afd3c7be.png"} 返回三个字段   filename  id 和url   问题是key是\/documents\/9f12a1d556d749ddaf5ad775afd3c7be.png     我要修改的是filename啊啊啊

**Comment by f630088281** [comment]
fname上传的原始文件名   不会改。。。<file>原文件名。对于没有文件名的情况，建议填入随机生成的纯文本字符串。本参数的值将作为魔法变量$(fname)的值使用。
params.put("x:custom_fields", str_customfields);
params.put("x:youyu_token", uploadModel.getYouyu_token());
params.put("fname", str_filename);    问题出在哪里呢

**Comment by netdxy** [comment]
您好，您使用的使我们的最新版本的Android SDK吗 即qiniu-android-sdk-7.0.9.jar ,Android 默认文件上传大于512K会采用分片上传机制，之前版本的SDK中fname是不支持分片上传的，所以当文件大于512K的时候会显示为空或者为"fname"，你换成最新版的SDK再试一下，可以参考下：
https://github.com/qiniu/android-sdk
另外，参考下Android的依赖关系下：
1）qiniu-android-sdk-7.0.9 必须和 android-async-http-1.4.9 依赖，而 android-async-http-1.4.9 又必须依赖cz.msebera.android(即下载httpclient-4.4.1.1.jar)，所以使用最新的 7.0.9Android 依赖的是 android-async-http-1.4.9.jar 和httpclient-4.4.1.1.jar 和 happy-dns.jar
2）qiniu-android-sdk-7.0.7~7.0.8 依赖的是 android-async-http-1.4.6~1.4.8，而 android-async-http-1.4.6~1.4.8 不需要依赖cz.msebera.android所以使用 qiniu-android-sdk-7.0.7~7.0.8 只需要导入 android-async-http-1.4.6~1.4.8 和 happy-dns.jar

**Comment by f630088281** [comment]
用的就是7.0.9啊 传fname 改不了filename     然后多加了个x:filename魔法变量  本地服务器上改了filename

**Comment by longbai** [comment]
请问能否贴下完整的调用代码

**Comment by longbai** [comment]
已经修正了，麻烦看下
