### ISSUE TITLE
网络层可以考虑换成OkHttp

### ISSUE THREAD

**Issue by pzhangleo** [qiniu/android-sdk#165]
使用现在的网络层必须依赖httpclient的包，能否考虑使用OkHttp，尽量减少工程引入的依赖包数量。

**Comment by longbai** [comment]
本地有写一个 okhttp的，但dns解析这块 okhttp 只有2.6 才加进来，所以搁置了，之后会换到okhttp, 但要2.6以上

**Comment by pzhangleo** [comment]
Ok，注意下Okhttp快要release 3.0版本，有不少api的变动。

**Comment by hnlbxb2004** [comment]
对于这种官方的sdk ，如非必须建议尽量少用第三方的一些依赖包。毕竟一般情况下，官方的sdk 业务量是相对来说很少的，用其他的一些依赖包，显得太过臃肿，我就仅仅加一个上图图片的功能，就要引入将近1MB 的依赖包，而且还是三个。（个人建议）

**Comment by longbai** [comment]
@hnlbxb2004 多谢建议，这个是有规划，依赖包 下一步只会有okhttp, 另外 happydns 是我们自己的包，只是独立出来。所以外部依赖就只有http部分。

**Comment by longbai** [comment]
@pzhangleo 短期内 3.0 不会考虑。

**Comment by longbai** [comment]
已经更换 7.1.x

**Comment by Ctrl-Space** [comment]
我的项目中就是 okhttp3.1.2 ，你这样不升级，我的项目就会有两个okhttp 存在，对于Android 65535 方法数来说是个很大的压力。

**Comment by longbai** [comment]
@Ctrl-Space, 收到了，我们看下

**Comment by pzhangleo** [comment]
OkHttp3的支持有时间表么？多谢

**Comment by Ctrl-Space** [comment]
其实我第二天才发现，仅仅用作上传的话，是不需要SDK的，所以，直接HTTP协议传就好了，可以继续用自己的网络库。
