### ISSUE TITLE
可否把网络请求库独立成一个模块

### ISSUE THREAD

**Issue by lijy91** [qiniu/android-sdk#166]
类似于Retrofit，封闭多个版本的网络请求库，使用的时候根据自己的需要选择

https://github.com/square/retrofit/tree/master/retrofit-converters

**Comment by longbai** [comment]
你这个比较激进，我现在是隔离的；因为 一些依赖关系，各库接口不一，不方便把这块搞得很复杂。后面 会改为okhttp. 即使是retrofit 也是默认用okhttp.
