### ISSUE TITLE
建议增加同步上传功能

### ISSUE THREAD

**Issue by liyzay** [qiniu/android-sdk#167]
建议增加同步上传功能，因为后台线程并不只是上传数据到七牛服务器，还要上传数据到自己的服务器。
现在使用异步上传，需要：
1、一个线程从自己服务器获取上传凭证；
2、利用上传凭证上传数据到七牛服务器；
3、再开一个线程上传七牛返回的数据到自己的服务器。
如果使用同步上传的话，那么只需要一个线程就够了。

**Comment by longbai** [comment]
这是一个事务，跟底层是否使用异步没多大关系，您可以加个semaphore 来达到同样效果，具体可参考 单元测试， 参考 https://github.com/qiniu/android-sdk/blob/master/library/src/androidTest/java/com/qiniu/android/FormUploadTest.java#L38
