### ISSUE TITLE
如何避免重复上传

### ISSUE THREAD

**Issue by liyzay** [qiniu/android-sdk#170]
已经找到etag算法，但是如何使用？

**Comment by longbai** [comment]
请问能详细描述下问题么？ 多谢了

**Comment by liyzay** [comment]
现在的情况是，已经上传到七牛服务器的文件，第二次上传的时候还是会上传一遍，这样导致流量和时间的浪费。请问怎样才能避免第二次的重复上传？

**Comment by longbai** [comment]
目前没什么特别好的方案避免
