### ISSUE TITLE
我就用个上传文件就要三个包？

### ISSUE THREAD

**Issue by renshaodong** [qiniu/android-sdk#171]

**Comment by longbai** [comment]
happydns 是 为了方便使用 独立出来的。 async http 是之前的依赖，现在 因为 升级 android ，原有的httpclient 不能使用，临时增加的http client。 目前 主分支改为 只依赖okhttp 了，但还没有release 出来。

**Comment by renshaodong** [comment]
赶紧换吧  我用http client 1.4.9还报错最后还加了4.4.1的才能用

**Comment by Songziyuan** [comment]
用HttpUrlConnection不好吗？就一个上传图片的SDK，搞的应用大了这么多。
内部做一个switch，Android版本大于2.3用HttpUrlConnection，小于2.3用HttpClient。

**Comment by longbai** [comment]
httpurl connection 使用 https 整合 外部dns 无法做到。

**Comment by renshaodong** [comment]
图片传到了七牛服务器 只能用它的sdk啊

**Comment by longbai** [comment]
@Songziyuan 您的想法 我理解，后面 我们会考虑下。

**Comment by longbai** [comment]
okhttp 的版本 已经 release
