### ISSUE TITLE
新手求一个下载私有文件的示例代码

### ISSUE THREAD

**Issue by zdd** [qiniu/android-sdk#187]
文档写的太简单了，加几行示例代码吧。

**Comment by forrest-mao** [comment]
@zdd android-sdk 没有提供鉴权签名的实现，因为涉及到鉴权的签名操作还是不建议在客户端实现，服务端使用java-sdk实现私有链接的demo可以参考 http://developer.qiniu.com/docs/v6/sdk/java-sdk.html#private-download ；另外android端的上传demo可以参考 https://github.com/qiniudemo/qiniu-lab-android 中的 [activity文件夹](https://github.com/qiniudemo/qiniu-lab-android/tree/master/QiniuLab/app/src/main/java/com/qiniu/qiniulab/activity)下的示例代码。

**Comment by zdd** [comment]
你的意思是不是说，Android端 无法实现私有文件下载？
