### ISSUE TITLE
取消正在上传的文件延迟比较高啊 ,有时候都暂停不了啊  (是不是和分片上传有关系 还有就是网络的状况啊)

### ISSUE THREAD

**Issue by chenfeixx** [qiniu/android-sdk#189]

**Comment by longbai** [comment]
分片上传可以取消的。网络状况是什么意思？

**Comment by chenfeixx** [comment]
就是在网络不好的情况下   取消比较慢

**Comment by longbai** [comment]
这个 我们 后面 会优化下

**Comment by jzyu** [comment]
也遇到此问题，上传进度提示界面现在是要等到取消callback调进来才关闭，结果网络不好情况下，点取消，很容易就悲剧了，卡死。。。

**Comment by longbai** [comment]
@jzyu 囧，再优化也不是立即就回调，这个还是建议上层处理下比较好。

**Comment by jzyu** [comment]
明白哦，点取消关闭等待界面先 @longbai

**Comment by lazy-ape** [comment]
遇到同样的问题，现在还没有解决吗？设置取消后根本没效果，UpCancellationSignal中的isCancelled()，会被调用很多次，都是返回true了还是没有取消上传。。。

**Comment by tengqiniu** [comment]
使用我们的最新版本SDK看下呢，我这边使用最新版本SDK测试是可以的了。
