### ISSUE TITLE
7.0.9版的例子里，断点续传，一点击暂停后就提示报错，断点存储文件不存在，是我这边配置错了还是怎么回事呢？

### ISSUE THREAD

**Issue by hdjtdxwt** [qiniu/android-sdk#193]
红米2手机  已经 模拟器都是这样的错，用命令行进去那个目录，确实有那么一个文件的！报错的提示是：java.io.FileNotFoundException: /data/data/com.qiniu.qiniulab/files/QiniuAndroid/Mzc3TkFrRnpjNDVRampYQ0FGYWJ5SWxVZlVNPS5wcm9ncmVzcw==: open failed: ENOENT (No such file or directory)

实际上有那么一个文件，是不是    -rw------   这个权限的问题

红米2手机进不去那个目录，提示没权限

**Comment by longbai** [comment]
我们看下

**Comment by clouddxy** [comment]
您好，我们这边测试7.0.9版断点续传是正常的，你们有加这个权限吗
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
另外，请检查下记录断点的文件路径是否是正确的。

**Comment by hdjtdxwt** [comment]
在执行这一步的时候，提示400 的错误，文档说实体格式错误，但是确实是5个块的最后一个分片返回的ctx组成的一个串，不知道为什么  app这个model和qiniuuplib是相关的代码，QiNiuServer.rar是服务器端的代码，token是去后台获取的，表单上传可以，分片上传在最后一步会报错，就差这一步了！！！求解
从网易126邮箱发来的云附件
QiNiuDemo.rar (46.27M, 2016年5月6日 19:03 到期)
下载
QiNiuServer.rar (20.96M, 2016年5月6日 19:05 到期)
下载

**Comment by hdjtdxwt** [comment]
代码中在第三个Activity里才是有分片上传的，并且文件是固定手机里有的一个文件的，ip地址是在公司用的内网地址，重新发布要重新改，有空看看，谢谢！

**Comment by clouddxy** [comment]
您好，我们这边没有遇到这种现象，您那边是否方便抓下包看下然后给我们提交下工单，然后我们建议您升级使用我们的Android 7.1.2的SDK上传，最新版本会修复一些之前的bug。
