### ISSUE TITLE
找不到HttpManager?!  HttpManager类型是.class

### ISSUE THREAD

**Issue by FrancisShi** [qiniu/android-sdk#195]
错误信息：
16:32:15.853 [ERROR] [system.err] Warning: com.qiniu.android.http.HttpManager$3: can't find referenced class com.qiniu.android.http.HttpManager

依赖：
compile 'com.qiniu:qiniu-android-sdk:7.1.2'

**Comment by longbai** [comment]
能发下完整的log么，麻烦提交下apk 地址 到工单那里，我们看下

**Comment by FrancisShi** [comment]
7.1.2:定位过去发现居然是.class 怪不得了。
降到7.0.1是.java。build没问题

如果有人也遇到 可以换成7.0.1试试。。。

**Comment by clouddxy** [comment]
您好，Android 7.1.0 以后需要依赖切换到okhttp(2.6及以上)，com.qiniu.android.http包下没有HttpManager类，取而代之的是Client类，所以直接引用是会报错的，您直接使用http包下Client类new一个httpManager就可以了，可以参考下面的Tets中的代码:
https://github.com/qiniu/android-sdk/blob/a874c6612e5d1e10f3625f3dca46a636ca32b8c9/library/src/androidTest/java/com/qiniu/android/HttpsTest.java#L25

**Comment by longbai** [comment]
这个是我们内部实现的类，不建议对外使用的
