### ISSUE TITLE
Glide无法 加载图片文件

### ISSUE THREAD

**Issue by longtaoge** [qiniu/android-sdk#202]
图片文件上传到七牛后返回的地址为  
https://7xtqd2.com1.z0.glb.clouddn.com/Fq-9Un4Uznz3Q2RYWb3aAqUhfMYi?e=1465743881&token=wQknukoe-lwcjLKEnsBz-BrL61M1BEMP0Gq_M2qP:VU_9enwWk-H5_TMbq1IXcGMREyE=

用Glide 无法直接加载
改为https 协议仍然无法正常加载，但是浏览器可以正常显示

**Comment by longbai** [comment]
token 包含 协议签名的，本来就不是http 域名，为啥要用https 访问

**Comment by longtaoge** [comment]
长话短说，Glide 加载这个地址 显示不出图片

**Comment by longbai** [comment]
这个域名 本来就不是https 域名，https 域名请在portal 上自助申请

**Comment by longtaoge** [comment]
谢谢，我大致知道原回了，估计还要服务器重新配置

**Comment by tengqiniu** [comment]
好的，有什么问题也可以在工单上反馈给我们。
