### ISSUE TITLE
能否加入同步的上传方法？

### ISSUE THREAD

**Issue by WanghongLin** [qiniu/android-sdk#208]
现在只有异步的上传方法。

通过UploadOptions回调，能否加入同步的上传，一直等待其结束或者出错才返回。

七牛图片上传任务只是整个任务的一部分，我希望在一个自己开的线程里面完成整个任务（七牛图片上传任务只是一部分）。

这样子可以简化线程同步的问题。

估计这种应用场合很多人会碰到吧？

**Comment by longbai** [comment]
有两个方式
1 使用java sdk里面的上传代码，或者直接用java sdk，可以跑在android 上的
2 增加semaphore 将 异步变成同步就好了。
