### ISSUE TITLE
安卓这边如何实现视频上传转码压缩等处理

### ISSUE THREAD

**Issue by aaironman** [qiniu/android-sdk#209]
安卓这边如何实现视频上传转码压缩等处理，我看java是有的，不知道android七牛Sdk有没有相应的方法，还是获取java后台那边给的token，后台处理

**Comment by peaceful321** [comment]
你好，

Android 这边如果希望 进行转码处理， 思路如下：

1. 服务端java 获取token的时候，设置好 persistentFops 和 persistentPipeline 这两个上传策略，具体可以查看我们的说明文档：

http://developer.qiniu.com/article/developer/security/put-policy.html

2.android 这边调用 服务端的接口，获取服务端 的token， 然后只执行上传操作（通过UploadManager对象的put方法）

**Comment by duwurensheng010** [comment]
Android本地能否直接处理视频，把处理完的视频上传给服务端
