### ISSUE TITLE
Android SDK如何覆盖上传

### ISSUE THREAD

**Issue by hgang** [qiniu/android-sdk#212]
用同一key多次上传不同的文件，提示：file exist。如何调用SDK完成覆盖上传呢？

**Comment by longbai** [comment]
需要token 指定为 key级别

**Comment by cike2056** [comment]
"需要token 指定为 key级别"怎么解释？

**Comment by longbai** [comment]
policy里的scope 改下

**Comment by hgang** [comment]
需要后台处理，后台返回的token决定了能否覆盖上传。
