### ISSUE TITLE
实例化UploadManager导致activity无响应，应用崩溃

### ISSUE THREAD

**Issue by ypf168326** [qiniu/android-sdk#213]
根据demo代码，在oncreate()方法中实例化UploadManager对象直接导致activity无响应，app崩溃。请问这个是什么原因？
Activity oncreate()方法
[@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mContext = this;
        UploadManager mUploadManager = new UploadManager();
         Log.e("qiniu",mUploadManager.toString());
    }](url)

gradle 配置
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile files('libs/pldroid-camera-streaming-1.7.0.jar')
    compile files('libs/com.umeng.message_v2.8.1.jar')
    compile files('libs/org.apache.http.legacy.jar')
    compile files('libs/MiPush_SDK_Client_2_2_21.jar')
    compile files('libs/umeng-analytics-v5.6.4.jar')
    compile files('libs/fastjson-1.1.38.jar')
    compile files('libs/ormlite-android-4.48.jar')
    compile files('libs/ormlite-core-4.48.jar')
    compile files('libs/ormlite-jdbc-4.48.jar')
    compile files('libs/andbase.jar')
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.jph.takephoto:takephoto_library:2.0.3'
    compile 'com.squareup.okio:okio:1.9.0'
    compile 'com.squareup.wire:wire-runtime:2.1.2'
    compile 'com.android.support:design:23.4.0'
    compile 'com.qiniu:happy-dns:0.2.7'
    compile 'com.qiniu:qiniu-android-sdk:7.2.+'
    compile 'com.squareup.okhttp3:okhttp:3.4.1'

}

**Comment by longbai** [comment]
这个不会有任何网络操作，而且 单元测试也都OK，能通过工单发个demo包过来么？

**Comment by ypf168326** [comment]
你说的没错，一开始确实有问题，找了半天原因也不知道什么问题，后来把happydns更新到最新版本解决了。

2016年8月21日星期日，Bai Long <notifications@github.com> 写道：

**Comment by longbai** [comment]
请问下 原来是 使用 happydns什么版本？我看下

**Comment by ypf168326** [comment]
当时用的是七牛的happydns 0.2.6的版本，估计是jar冲突导致的，换成0.2.10就好了。

**Comment by tengqiniu** [comment]
好的，感谢您提供的宝贵意见。
