### ISSUE TITLE
似乎无法分片上传 byte[] 类型的数据？

### ISSUE THREAD

**Issue by zshbleaker** [qiniu/android-sdk#214]
现有需求是分析每一片请求的网络状况。分析了 SDK 实现后，似乎 byte[] 数据直接使用了 FormUploader 与 OkHttp 的 multipart 进行上传，没有根据文档 http://developer.qiniu.com/article/index.html#kodo-api-handbook 描述的方式进行分片操作。请问是我理解错误还是的确如此？

**Comment by longbai** [comment]
是的，因为1 byte 数据一般都不大，2 无法做断点记录的持久化，所以 不会采用分片上传的方式

**Comment by zshbleaker** [comment]
了解
