### ISSUE TITLE
七牛 7.3.0 的cpu架构的 .so库在哪？PLDroidPlayer用的版本是哪个？

### ISSUE THREAD

**Issue by lizhifeng-sky** [qiniu/android-sdk#223]
qq:1740512001  tel: 13162137315
如有链接欢迎发我一份 谢谢
我在用7.3.0的时候PLDroidPlayer版本是1.3.2  出异常 classnotfundException :com.qiniu.pili.droid.report.QosEnv

**Comment by lizhifeng-sky** [comment]
我做的功能是播放时hls视频  videoview用的是PLVideoview

**Comment by longbai** [comment]
。。。 请到 pili-engineering 的 项目中看，这里没有so
