### ISSUE TITLE
error:incorrect region, please use up-z2.qiniu.com}

### ISSUE THREAD

**Issue by denghewenai** [qiniu/android-sdk#224]
我从maven上添加的依赖，zone源码中没有加入up-z2.qiniu.com

**Comment by longbai** [comment]
新版已经加入进来，麻烦确认下。

**Comment by denghewenai** [comment]
OK，可以了。

**Comment by RuffianZhong** [comment]
@longbai 我用studio  
compile 'com.qiniu:qiniu-android-sdk:7.2.+'
还是没有啊。
![image](https://cloud.githubusercontent.com/assets/7261019/21519110/b74d6e02-cd25-11e6-9207-29c0a0beabf8.png)
不是有一个自动获取zone的吗？这里也没有，我看到SDK包版本是7.2.3了，，，
