### ISSUE TITLE
你们的文档也是够low啊

### ISSUE THREAD

**Issue by AnlieMelody** [qiniu/android-sdk#231]

**Comment by lilanjun2016** [comment]
hi~  您是看文档哪部分觉得不清楚嘛，有不清楚的地方，您可以说下。

**Comment by AnlieMelody** [comment]
整体上就是乱，对比下leancloud的文档简直差太远。读当然读清楚了，不过是要花上多倍的时间。最大原因应该是sdk写的不好。

**Comment by longbai** [comment]
@AnlieMelody 请问您觉得sdk哪块写的有问题，我们改进下。

**Comment by Zihuatanejo50** [comment]
看了下安卓的文档，确实挺糟糕的，markdown说明文档写的很乱，贴了那么多代码，需要加超链接的地方又不加，找了半天！ @longbai

**Comment by tengqiniu** [comment]
感谢您提供的宝贵意见，这边会反馈给相关同事，去改进下。
