### ISSUE TITLE
多线程同时上传多文件，内容错乱

### ISSUE THREAD

**Issue by yueban** [qiniu/android-sdk#241]
同时上传 12 张图片，每个上传任务放在单独线程内进行，问题如下：
本地 filePath 与 Qiniu key 可以一一对应，但是存在两个不同 key 对应的图片内容相同的情况，即：
key1 → pic1
key2 → pic1
key3 → pic1

正常情况应为：
key1 → pic1
key2 → pic2
key3 → pic3

**Comment by jemygraw** [comment]
show me the code
