### ISSUE TITLE
7.3.2版本，ETag.file()方法计算2G大小的文件时，数组索引为负的错误，int长度溢出

### ISSUE THREAD

**Issue by xiaoyanqiang** [qiniu/android-sdk#242]
在ETag类里，有个stream()方法，里面有一句在文件长度很大的时候，产生int长度溢出
`byte[][] blocks = new byte[(int) (len + Configuration.BLOCK_SIZE - 1) / Configuration.BLOCK_SIZE][];`

譬如这里，我的文件为2.2G大小的zip包
len=2323435710
Configuration.BLOCK_SIZE 为默认值 4 * 1024 * 1024
`(int) (len + Configuration.BLOCK_SIZE - 1) / Configuration.BLOCK_SIZE`计算的结果为-469
`byte[][] blocks = new byte[-469][]` ........产生索引错误

建议尽快修复这问题，否则大文件计算就会有问题

**Comment by jemygraw** [comment]
FIXED in d378e5047b62c5e49045f34ae5258bd6cc6a25bb
>=7.3.3 is ok
