### ISSUE TITLE
小米手机能成功上传，华为手机就上传报错，如下是错误信息，不得不说七牛的文档真的不清晰

### ISSUE THREAD

**Issue by CodeSmell65535** [qiniu/android-sdk#253]
04-18 09:00:09.644 32756-32756/com.linkerlab.water D/QiniuUtil: 1492477196667.jpg, {ver:7.3.0,ResponseInfo:1492477204531195,status:579, reqId:EUQAAMhyG4gdWLYU, xlog:RA:183.131.7.18:80;body:5;s.ph;s.put.tw;s.put.tr:27;s.put.tw;s.put.tr:25;s.ph;PFDS:26;PFDS:28;rs33_11.sel;rwro.ins/same entry;rs33_11.sel;rwro.get;MQ;RS.not:;RS:1;rs.put:7;rs-upload.putFile:38;QINIUPROXY:1/502;UP.CB:2;up:/upload callback failed;UP:49/579;NUPROXY:313/579, xvia:, host:upload.qiniu.com, path:/, ip:/122.13.18.67:80, port:80, duration:1525.000000 s, time:1492477209, sent:0,error:{"callback_url":"qiniu/callback","callback_bodyType":"application/x-www-form-urlencoded","callback_body":"project_id=299\u0026stage=1\u0026question_number=9\u0026type=project_img\u0026name=1492477196667.jpg","token":"","err_code":502,"error":"Post http://qiniu/callback: dial tcp: lookup qiniu on 127.0.0.1:53: no such host","hash":"FvqhvvBTLL08LOlHFsAZxtrcYGtf","key":"1492477196667.jpg"}}, {"error":"{\"callback_url\":\"qiniu\/callback\",\"callback_bodyType\":\"application\/x-www-form-urlencoded\",\"callback_body\":\"project_id=299\\u0026stage=1\\u0026question_number=9\\u0026type=project_img\\u0026name=1492477196667.jpg\",\"token\":\"\",\"err_code\":502,\"error\":\"Post http:\/\/qiniu\/callback: dial tcp: lookup qiniu on 127.0.0.1:53: no such host\",\"hash\":\"FvqhvvBTLL08LOlHFsAZxtrcYGtf\",\"key\":\"1492477196667.jpg\"}"}

**Comment by ReikyZ** [comment]
这个是网关错误，检查一下手机的网络配置，或者更换网络

**Comment by jemygraw** [comment]
七牛的callbackUrl填错了，导致上传完毕无法回调成功，所以报错。
