### ISSUE TITLE
Android用syncPut同步上传，通过UploadOptions获取不到上传进度

### ISSUE THREAD

**Issue by szhupeng** [qiniu/android-sdk#275]
同步上传UploadOptions中设置获取上传进度没有回调

**Comment by ReikyZ** [comment]
同步上传没有进度回调；上传结果通过 ResponseInfo 获取。

**Comment by szhupeng** [comment]
那我自己开线程用七牛同步上传api进行上传，怎样监听上传进度

**Comment by ReikyZ** [comment]
上传进度只能通过 UpProgressHandler 中 progress 回调方法获取，在 UploadManager.put() 时回调。

**Comment by szhupeng** [comment]
你们这个设计不合理啊，我现在自己用线程池调用syncPut同步上传拿不到进度，而必须调用put异步上传才能，这样同步上传接口岂不是有很大的弊端

**Comment by ReikyZ** [comment]
这个方法用于较小文件的上传，结果能够比较即时的返回，并不需要上传的进度

**Comment by szhupeng** [comment]
这种考虑不合理，即使文件再小，上传也会受到网速影响，如果网速不够快，进度也是需要的，另外上传进度本身即使是可选的，但是功能还是要给出来，毕竟有部分人的需求是要用同步上传但是又需要进度的，希望你们能加上，因为我现在需要用到同步上传，也需要进度条

**Comment by ReikyZ** [comment]
在网络不够快的场景下，使用put方法就可以获取进度，上传结果可以通过回调处理。

**Comment by szhupeng** [comment]
现在问题是我不需要使用put，我需要使用syncPut并且需要获取进度

**Comment by zshbleaker** [comment]
@szhupeng 目前 SDK 提供了两种上传，一个同步一个异步；对于异步的操作，很容易开一个 listener 去把进度等信息回调上去；如果是同步，那么很难实时准确的实现信息回调；特别是同步场景往往用于小文件上传，如果非要实现同步的进度回调，那么很有可能文件都传完了，客户端才收到一半的进度，这无疑是很影响用户体验的。

对于你们的场景，小文件上传完全可以使用虚假的进度条，在收到上传完成的回调时把进度调到 100% 就好。
