### ISSUE TITLE
设置isCancelled = true后还是一直不停回调isCancelled，如何彻底停止？

### ISSUE THREAD

**Issue by yanyiqun001** [qiniu/android-sdk#280]

**Comment by jemygraw** [comment]
给下你的 CancellationHandler 的实现代码。

**Comment by yanyiqun001** [comment]
public void uploadFile(final String[] filePath, String token, Map<String, String> map, final UploadListener uploadListener) {
        for (int i = 0; i < filePath.length; i++) {
            final int finalI = i;
            //文件命名 当前时间的毫秒数加文件名
            String fileName = System.currentTimeMillis() + filePath[i].substring(filePath[i].lastIndexOf("/") + 1);
            uploadManager.put(filePath[i], fileName, token,
                    new UpCompletionHandler() {
                        public void complete(String key,
                                             ResponseInfo info, JSONObject res) {
                            if (info.isOK() == true) {
                                uploadListener.onSuccess(key, info, res, finalI);
                            } else if (info.statusCode == 401) { //token失效
                                uploadListener.isTokenExpried();
                                ToastUtil.showShortToast("token失效");
                            } else {
                                uploadListener.onFailure(key, info, res, finalI);
                            }
                        }
                    }, new UploadOptions(map, null, false,
                            new UpProgressHandler() {
                                public void progress(String key, double percent) {
                                    int mProgress=0;
                                    int progress = (int) (percent * 100);
                                    if (progress == 100) {
                                        mCount++;
                                        mProgress= (int) (((float)mCount/filePath.length)*100);

                                    }
                                    uploadListener.onProgress(mProgress, mCount, filePath.length);
                                }
                            }, new UpCancellationSignal() {
                        @Override
                        public boolean isCancelled() {
                            uploadListener.onCancel(isCancelled);
                            Log.i("qiniu","isCancelled"+isCancelled);
                            return isCancelled;

                        }
                    }));
        }
    }

    public void cancel() {
        isCancelled = true;
    }


外部调用cancel()

**Comment by yanyiqun001** [comment]
````
public void uploadFile(final String[] filePath, String token, Map<String, String> map, final UploadListener uploadListener) {
for (int i = 0; i < filePath.length; i++) {
final int finalI = i;
//文件命名 当前时间的毫秒数加文件名
String fileName = System.currentTimeMillis() + filePath[i].substring(filePath[i].lastIndexOf("/") + 1);
uploadManager.put(filePath[i], fileName, token,
new UpCompletionHandler() {
public void complete(String key,
ResponseInfo info, JSONObject res) {
if (info.isOK() == true) {
uploadListener.onSuccess(key, info, res, finalI);
} else if (info.statusCode == 401) { //token失效
uploadListener.isTokenExpried();
ToastUtil.showShortToast("token失效");
} else {
uploadListener.onFailure(key, info, res, finalI);
}
}
}, new UploadOptions(map, null, false,
new UpProgressHandler() {
public void progress(String key, double percent) {
int mProgress=0;
int progress = (int) (percent * 100);
if (progress == 100) {
mCount++;
mProgress= (int) (((float)mCount/filePath.length)*100);

                                }
                                uploadListener.onProgress(mProgress, mCount, filePath.length);
                            }
                        }, new UpCancellationSignal() {
                    @Override
                    public boolean isCancelled() {
                        uploadListener.onCancel(isCancelled);
                        Log.i("qiniu","isCancelled"+isCancelled);
                        return isCancelled;

                    }
                }));
    }
}

public void cancel() {
    isCancelled = true;
}
````
外部调用cancel()

**Comment by jemygraw** [comment]
```
 uploadListener.onCancel(isCancelled);
```
这个在做什么

**Comment by yanyiqun001** [comment]
没有做任何事
