### ISSUE TITLE
在部分WiFi关键下，高概率出现上传失败 upload-nb.qiniup.com: the dns server cant support recursion

### ISSUE THREAD

**Issue by ml-bright** [qiniu/android-sdk#281]
在WiFi环境下（4G正常）：同时上传多张图片，一次上传一张，上传到一半左右的时候经常出现：upload-nb.qiniup.com: the dns server cant support recursion 这个错误。

错误码：-1003

**Comment by jemygraw** [comment]
好的，收到，我们调查看看。
