### ISSUE TITLE
上传过程中速度降低

### ISSUE THREAD

**Issue by csbz17027** [qiniu/android-sdk#288]
我批量上传50多张图片文件，文件大小在150KB左右，每次循环上传10张，前面37张左右速度很快，然后速度突然就降下来了，用wifi和4G都尝试过，现象一样，请问这可能是哪种原因造成的？
上传方法如下
  private void startUpload(List<String> list) {
    time = 0;
    for (String filePath : list) {
      String fileKey = filePath.substring(filePath.lastIndexOf("/") + 1);
      uploadManager.put(filePath, fileKey, imgToken, (key, responseInfo, response) -> {
        if (!responseInfo.isOK()) {
          CrashHandler.postCatchedException(responseInfo.toString());
        }

        ++time;
        if (time == list.size()) {
          filesPathList.removeAll(list);
          if (filesPathList.size() > 0) {
            uploadHandler.sendEmptyMessage(0);
          }
        }
        progressHandler.sendEmptyMessage(0);
      }, null);
    }
  }

**Comment by ReikyZ** [comment]
sdk 没有限制上传速度的机制，麻烦检查是否是上行带宽，或者多线程影响了上传速度。
