### ISSUE TITLE
Etag计算方法中，没有对异常情况进行io关闭

### ISSUE THREAD

**Issue by gordonpro** [qiniu/android-sdk#289]
https://github.com/qiniu/android-sdk/blob/a61dc8815dd400ebd92cc939d4626c2c3b14d7c6/library/src/main/java/com/qiniu/android/utils/Etag.java#L55

如果遇到`IOException` 直接throw到上层，但是那个FileInputStream没有关闭

**Comment by gordonpro** [comment]
通常都是try finally 吧

**Comment by ReikyZ** [comment]
感谢反馈，目前可以使用 stream(InputStream in, long len) ，使用后手动close 一下；我们再后续版本完善这部分。
