### ISSUE TITLE
上传文件失败，返回的statusCode为613代表什么意思？

### ISSUE THREAD

**Issue by csbz17027** [qiniu/android-sdk#293]
完整的返回信息如下，还请为我答疑：
{ver:7.3.3,ResponseInfo:1516589854645778,status:613, reqId:nwwAAL2W6WcIBAwV, xlog:s.ph;s.ph;PFDS;PFDS;PTFDM:38;s.gh;PFDS/613;s.gh;PFDS/613;PFDS/620;AUTHPROXY_xs_out:3/620;PTFDM:23;PTFDS;body;rs36_18.sel:4/not found;rdb.g/no such key;DBD/404;v4.get/Document not found;rs37_18.sel:3/not found;rs37_18.ups:4/E11000 duplicate key error colle;rwro.upsc:12/cond not match;RS:12/613;rs.put:13/cond not match;up:;UP:87/613, xvia:vdn-tj-cnc-1-2, host:upload.qiniu.com, path:/mkfile/1749192/mimeType/YXBwbGljYXRpb24vb2N0ZXQtc3RyZWFt/fname/YW5kcm9pZF9pbWdfMTA1YTQyXzE1MTY1OTEyMzA0NTI=/key/YW5kcm9pZF9pbWdfMTA1YTQyXzE1MTY1OTEyMzA0NTI=, ip:/220.194.102.99:80, port:80, duration:227.000000 s, time:1516591608, sent:196,error:cond not match}

**Comment by jemygraw** [comment]
这种问题一般是文件上传的同时，空间有对文件进行处理的操作，需要你对应看下。
