### ISSUE TITLE
7.0手机上传出错。6.0，8.0正常

### ISSUE THREAD

**Issue by Liaox** [qiniu/android-sdk#294]
info如下：
{ver:7.3.10,ResponseInfo:1517041230827394,status:0, reqId:, xlog:, xvia:, host:, path:, ip:, port:0, duration:0 s, time:1517041594, sent:0,error:Attempt to invoke virtual method 'int org.json.JSONObject.getInt(java.lang.String)' on a null object reference}

错误日志如下：
System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
01-27 16:26:34.865 19727-22319/? W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
01-27 16:26:34.865 19727-22319/? W/System.err:     at okhttp3.RealCall.execute(RealCall.java:69)
01-27 16:26:34.865 19727-22319/? W/System.err:     at com.qiniu.android.http.Client.send(Client.java:364)
01-27 16:26:34.865 19727-22319/? W/System.err:     at com.qiniu.android.http.Client.syncGet(Client.java:345)
01-27 16:26:34.865 19727-22319/? W/System.err:     at com.qiniu.android.common.AutoZone.getZoneJsonSync(AutoZone.java:45)
01-27 16:26:34.865 19727-22319/? W/System.err:     at com.qiniu.android.common.AutoZone.preQueryIndex(AutoZone.java:113)
01-27 16:26:34.865 19727-22319/? W/System.err:     at com.qiniu.android.common.AutoZone.preQuery(AutoZone.java:144)
01-27 16:26:34.865 19727-22319/? W/System.err:     at com.qiniu.android.storage.FormUploader.syncUpload0(FormUploader.java:243)
01-27 16:26:34.865 19727-22319/? W/System.err:     at com.qiniu.android.storage.FormUploader.syncUpload(FormUploader.java:198)
01-27 16:26:34.865 19727-22319/? W/System.err:     at com.qiniu.android.storage.UploadManager.syncPut(UploadManager.java:225)

**Comment by jemygraw** [comment]
这个如果可以提供一个抓包文件分析下最好了

**Comment by Liaox** [comment]
@jemygraw 抓包工具那些我都没有装，提供不了。日志就是这些了。手机是三星s6edge。系统7.0

**Comment by ReikyZ** [comment]
可以自定义 X509TrustManager 类跳过验证。

**Comment by hfg5961107** [comment]
使用的sdk调用的上传图片怎么修改这个X509TrustManager跳过验证。
