### ISSUE TITLE
请问下官方有计划发 Cordova 版本么？

### ISSUE THREAD

**Issue by pengkobe** [qiniu/android-sdk#296]
在 github 找了下，发现了 2 个废弃的库，基本上不维护了，基于 cordova 开发的 hybrid app 越来越多，建议出个 cordova 版本，这块极光做的不错，也得到了非常多的 star. 强烈建议搞起来！  造福开发者，增加七牛收入~~~

**Comment by ReikyZ** [comment]
目前还没有计划

**Comment by pengkobe** [comment]
好的，谢谢回复。
