### ISSUE TITLE
AndroidDnsServer类报错，java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by csbz17027** [qiniu/android-sdk#302]
手机是Nokia 8 Sirocco
log如下：

# OkHttp Dispatcher(2973)

java.lang.StringIndexOutOfBoundsException

String index out of range: -1

1 java.lang.String.substring(String.java:1975)
--
2 com.qiniu.android.dns.local.AndroidDnsServer.getByCommand(AndroidDnsServer.java:37)
3 com.qiniu.android.dns.local.AndroidDnsServer$1.resolve(AndroidDnsServer.java:113)
4 com.qiniu.android.dns.DnsManager.queryInternal(DnsManager.java:168)
5 com.qiniu.android.dns.DnsManager.query(DnsManager.java:116)
6 com.qiniu.android.dns.DnsManager.queryInetAdress(DnsManager.java:213)
7 com.qiniu.android.http.Client$1.lookup(Client.java:67)
8 okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
9 okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
10 okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
11 okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:213)
12 okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
13 okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
14 okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
15 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
16 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
17 okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
18 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
19 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
20 okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
21 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
22 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
23 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
24 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
25 okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
26 okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
27 okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
28 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
29 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
30 java.lang.Thread.run(Thread.java:764)

**Comment by jemygraw** [comment]
可以反馈下sdk版本么

**Comment by jemygraw** [comment]
换到7.3.12最新版本看看，我估计是因为依赖的happy dns库处理并发的时候导致的问题。
