### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by zhuzhushang** [qiniu/android-sdk#303]
总是报reset,

![360 20180509144402694](https://user-images.githubusercontent.com/11988439/39799526-24453370-5397-11e8-8458-9950b2e87af0.jpg)

` private void uploadFile(QiNiuUploadInfo qiNiuUploadInfo) {

        String path = android.os.Environment.getExternalStorageDirectory().getPath()+"/sunshine_in_the_rain.mp3";
        File file = new File(path);
        if(file.exists()){

            String key = qiNiuUploadInfo.getData().getFiles().get(0).getOrg_name();
            String token = "";
            try {
                token = getToken(qiNiuUploadInfo.getData().getC_data().getC_paramters().get(0));
            } catch (Exception e) {
                e.printStackTrace();
            }
//            UploadOptions uploadOptions = new UploadOptions()
            LogUtils.e("---->token = "+token);
            if(StringUtils.isEmpty(token)){

                return;
            }

            UploadOptions uploadOptions = new UploadOptions(null,"audio/x-mpeg",false,null,null);

            mUploadManager.put(file, key, token, new UpCompletionHandler() {
                @Override
                public void complete(String key, ResponseInfo info, JSONObject response) {

                    //res包含hash、key等信息，具体字段取决于上传策略的设置
                    if(info.isOK()) {
                        Log.i("qiniu", "Upload Success");
                    } else {
                        Log.i("qiniu", "Upload Fail");
                        //如果失败，这里可以把info信息上报自己的服务器，便于后面分析上传错误原因
                    }
//                    Log.i("qiniu", key + ",\r\n " + info + ",\r\n " + response.toString());
                    LogUtils.e("------>error = "+info.error);

                }
            },uploadOptions);

        }

    }`

**Comment by jemygraw** [comment]
收到，这个问题我们看下。

**Comment by jemygraw** [comment]
目前问题已解决，麻烦重试看看。

**Comment by zhuzhushang** [comment]
我试了手机上没有问题，在公司平板上会有这种情况。
需要你们分析分析下为什么会有这种情况。下列是日志
[新建文本文档 (2).txt](https://github.com/qiniu/android-sdk/files/1987762/2.txt)

**Comment by zhuzhushang** [comment]
采用表单的形式是可以上传的，但是表单没有进度。

**Comment by jemygraw** [comment]
现在平板还是不行么？把app kill掉试试看呢。

**Comment by jemygraw** [comment]
从你给的日志看，都是域名无法解析的错误，你看看平板连网OK么
