### ISSUE TITLE
error:file or data size is zero

### ISSUE THREAD

**Issue by qiangxi** [qiniu/android-sdk#306]
具体报错：
```
{ver:7.3.12,ResponseInfo:1533521690917648,status:-6, reqId:, xlog:, xvia:, host:, path:, ip:, port:80, duration:0 s, time:1533521899, sent:0,error:file or data size is zero}
```
很多用户报这个错，但实际上这个文件确实存在，请问咋回事啊，要被产品经理烦死了~

**Comment by Yexiangxu** [comment]
为什么这个close了，这个现在用的7.3.15的版本，也是报错这个，第一次报错这个然后再上传又可以，烦死了

**Comment by bachue** [comment]
@Yexiangxu 能否升级到 7.4.x 或 7.5 以后再试试看？

**Comment by bachue** [comment]
@Yexiangxu 如果还有问题，建议给下你这边调用 sdk 的代码，我们检查下

**Comment by Yexiangxu** [comment]
我看网上有很多用七牛云提了这个问题就以为是七牛云的问题。昨天查找之后发现不是七牛云的问题，部分手机在图片压缩（我用的是鲁班压缩）之后获取到的file.length=0，过几秒才能获取到file，具体原因还在查找，但是不是七牛云问题，不好意思打扰了哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Bachue Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 上午9:26
收件人:&nbsp;"qiniu/android-sdk"<android-sdk@noreply.github.com&gt;;
抄送:&nbsp;"Lazy_xu"<605568743@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [qiniu/android-sdk] error:file or data size is zero (#306)




@Yexiangxu 能否升级到 7.4.x 或 7.5 以后再试试看？

**Comment by bachue** [comment]
@Yexiangxu 没事哈
