### ISSUE TITLE
checkCrc参数无效

### ISSUE THREAD

**Issue by kolarbear** [qiniu/android-sdk#317]
FormUploader 类中的post方法，里面根本没有用到UploadOptions中的checkCrc参数！！！然后莫名奇妙的十次中有一次会给我报错406 crc32 check error!!!!!!!!!请尽快修复！！！

**Comment by zyyl** [comment]
求解决方案

**Comment by kolarbear** [comment]
> 求解决方案

解决方案就是避免你上传的文件跟你本地文件不一致

**Comment by JemyCheung** [comment]
这个默认就是会计算，sdk流程如下
1.本地计算crc32的值，上传中会携带这个值。param1
2.文件上传后服务端计算上传文件的crc32值，param2
3.服务端比较param1和param2，如果不一致，返回crc32校验错误

您这边收到返回406表示这个就是有问题的，可能被拦截或者上传过程中文件被篡改等 @kolarbear @zyyl
