### ISSUE TITLE
https方式调用上传后，取消上传，上传回调不执行

### ISSUE THREAD

**Issue by jinfengf** [qiniu/android-sdk#322]
使用https上传时,取消上传发现回调不执行，调试后发现是RetryAndFollowUpInterceptor里recover(e, streamAllocation, requestSendStarted, request)一直返回true，导致一直在重试。使用http模式时则没有该问题

**Comment by JemyCheung** [comment]
这个实测过，在test case中确实有出现，是由于okhttp版本导致，用4.x的版本就可以了，或者用http协议上传。
大致原因可以看这里 https://blog.csdn.net/JemyCheung/article/details/106662931
具体的还需要花时间看okhttp版本的更新 @jinfengf
