### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by smallfishfizz** [qiniu/android-sdk#328]
我有两个项目A、B，A为主项目，B为插件项目，A引用B。A、B都启用了混淆，我在B项目里使用了七牛sdk，在B里对七牛SDK做了混淆处理。在A中build项目时，出现如下图错误警告，请问是什么问题。谢谢~
![B七牛SDK混淆](https://user-images.githubusercontent.com/28420522/59910498-9d582f80-9444-11e9-96f1-a0325def7337.png)
![A build结果](https://user-images.githubusercontent.com/28420522/59910500-9df0c600-9444-11e9-959b-8ca4b6faf9c5.png)

**Comment by JemyCheung** [comment]
您确认一下项目的环境，这边测试是没有问题的 @smallfishfizz

**Comment by bachue** [comment]
该 Issue 先关闭，如果还有问题，可以重新打开
