### ISSUE TITLE
okhttp4.0.0的不兼容

### ISSUE THREAD

**Issue by yangfeng1994** [qiniu/android-sdk#337]
目前很多项目中，okhttp都已经更新了。现在如果用新版的okhttp，本项目会有一些方便被遗弃，就会报错，还需要自己将项目fork下载更改，比较耽误时间

**Comment by hamberluo** [comment]
#327

**Comment by JemyCheung** [comment]
升级到7.5.0已经解决，您试试 @yangfeng1994
