### ISSUE TITLE
华为mate20上传闪退，dnsPrefetcher空指针

### ISSUE THREAD

**Issue by victor1007** [qiniu/android-sdk#339]
产生原因：在创建Dns缓存目录/sdcard/dnschache时，文件夹创建失败，抛了IO异常，导致下一行的dnsPrefetcher没有初始化，后续使用dnsPrefetcher就空指针了。

**Comment by JemyCheung** [comment]
这个在review中了，可以catch异常直接return，后面判空一下处理 @victor1007

**Comment by victor1007** [comment]
嗯，这样不崩溃了，但上传功能也就用不了了。我用Environment类获取根目录的方式创建文件夹，m kdirs仍然返回false，读写权限和SD卡是否挂载都没问题，挺纳闷的，同样的方式在我自己的项目中创建文件夹就没事，暂时没找到原因，你们那边找到解决办法的话，麻烦回复下，谢谢。

**Comment by victor1007** [comment]
> 这个在review中了，可以catch异常直接return，后面判空一下处理 @victor1007

嗯，这样不崩溃了，但上传功能也就用不了了。我用Environment类获取根目录的方式创建文件夹，m kdirs仍然返回false，读写权限和SD卡是否挂载都没问题，挺纳闷的，同样的方式在我自己的项目中创建文件夹就没事，暂时没找到原因，你们那边找到解决办法的话，麻烦回复下，谢谢。

**Comment by JemyCheung** [comment]
1.这是一个单独的线程操作，这里catch住之后只要不崩溃理论上是不会影响上传功能的。
2.java的api，mkdirs不成功的话，应该是环境有点问题，rebuild一下试试。
感谢您提的issue，这边我们也找机器测试一下 @victor1007

**Comment by huangkaiqiao** [comment]
> 产生原因：在创建Dns缓存目录/sdcard/dnschache时，文件夹创建失败，抛了IO异常，导致下一行的dnsPrefetcher没有初始化，后续使用dnsPrefetcher就空指针了。

这个我解决了 Config.dnscacheDir =  "data/data/{ 这里填你的包名 }/qiniu/dnschache"
上传文件之前修改一下dns缓存配置
