### ISSUE TITLE
不支持Android 10 content 文件上传

### ISSUE THREAD

**Issue by jarhot1992** [qiniu/android-sdk#343]
不支持Android 10 content 文件上传

**Comment by SnowyTomorrow** [comment]
希望他们尽快兼容android 10

**Comment by wkk-knight** [comment]
希望兼容android 10  现在只能使用只能在清单文件application   标签添加`android:requestLegacyExternalStorage="true"`，这只是临时的解决方法

**Comment by YangSen-qn** [comment]
现在版本已经支持 Android10, 请升级至最新版本。 @jarhot1992
