### ISSUE TITLE
Do you know okhttp4.2.2 support android 21+

### ISSUE THREAD

**Issue by jtxuanshui** [qiniu/android-sdk#361]
So, the version 7.5.1 support only 21+ devices, not Android 4.0+
![image](https://user-images.githubusercontent.com/10495655/71455957-38eea200-27d2-11ea-92da-73502551d2c5.png)

**Comment by hply** [comment]
七牛云的脑残开发使用okhttp，却不会看别人文档，解决方法如下，如果需要使用最新版的7.5.2，可以如下依赖：
implementation 'com.squareup.okhttp3:okhttp:3.12.6'
implementation('com.qiniu:qiniu-android-sdk:7.5.2'){
        exclude module:"okhttp"
    }

**Comment by jtxuanshui** [comment]
哈，不用蹩脚的英文了，我是直接降级使用了
    implementation 'com.qiniu:qiniu-android-sdk:7.4.+'
    implementation "com.squareup.okhttp3:okhttp:3.12.0"

**Comment by JemyCheung** [comment]
![image](https://user-images.githubusercontent.com/37655628/87407289-8a3a7380-c5f4-11ea-8598-2e66c33b6e9f.png)
