### ISSUE TITLE
android9，上传图片报Network error during preQuery

### ISSUE THREAD

**Issue by cascoxbw** [qiniu/android-sdk#362]
{ver:7.5.0,ResponseInfo:1577864005618440,status:-1, reqId:, xlog:, xvia:, host:, path:, ip:, port:80, duration:0 s, time:1577864005, sent:0,error:Network error during preQuery, Please check your network or use http try again}

网络没问题，因为服务器的token我能顺利获取，所以请教下解决方法

**Comment by JemyCheung** [comment]
更新一下sdk到7.6.4或者7.4.6。相关版本差异看一下文档或者readme 应该可以解决

这个问题主要是dns解析或者网络访问不通时出现 @cascoxbw
