### ISSUE TITLE
readme错误引导提示

### ISSUE THREAD

**Issue by hply** [qiniu/android-sdk#363]
最新版7.5使用的okhttp，基于okhttp4.x , okhttp4.x官网都是说明了最低支持是android5.0+，你们却说你们是支持4.0+，太不严谨了，4.3亲测别处使用到okhttp的地方崩溃；
Requirements
OkHttp works on Android 5.0+ (API level 21+) and on Java 8+.

OkHttp depends on Okio for high-performance I/O and the Kotlin standard library. Both are small libraries with strong backward-compatibility.

We highly recommend you keep OkHttp up-to-date. As with auto-updating web browsers, staying current with HTTPS clients is an important defense against potential security problems. We track the dynamic TLS ecosystem and adjust OkHttp to improve connectivity and security.

OkHttp uses your platform's built-in TLS implementation. On Java platforms OkHttp also supports Conscrypt, which integrates BoringSSL with Java. OkHttp will use Conscrypt if it is the first security provider:

Security.insertProviderAt(Conscrypt.newProvider(), 1);
The OkHttp 3.12.x branch supports Android 2.3+ (API level 9+) and Java 7+. These platforms lack support for TLS 1.2 and should not be used. But because upgrading is difficult we will backport critical fixes to the 3.12.x branch through December 31, 2020.

**Comment by cuibg** [comment]
七牛开发已经感觉废材了，我们这项目用的他们的存储，用的他们的上传，部分手机上传极慢，现在也不解决，干什么吃呢，废材！

**Comment by JemyCheung** [comment]
您好，这个已经更新到7.6.x，相关readme也已经更新 @hply
