### ISSUE TITLE
无法关闭crc32校验。

### ISSUE THREAD

**Issue by zczhhhh** [qiniu/android-sdk#364]
从[文档](https://developer.qiniu.com/kodo/sdk/1236/android)里看，可以通过在uploadoptions里设置checkCrc来控制上传是否校验crc32的值。实测无法控制。
[FormUpload](https://github.com/qiniu/android-sdk/blob/7af63be9dc846ca3f50fc8b1b01ffc1700d34593/library/src/main/java/com/qiniu/android/storage/FormUploader.java)的put方法中，crc参数直接加在了请求里面。貌似与uploadoptions的设置没有关系。
```
        final UploadOptions options = optionsIn != null ? optionsIn : UploadOptions.defaultOptions();
        params.putFileds(options.params);
        long crc = 0;
        if (file != null) {
            try {
                crc = Crc32.file(file);
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            crc = Crc32.bytes(data);
        }
        params.put("crc32", "" + crc);
```

**Comment by JemyCheung** [comment]
sdk这个参数您可以忽略，这个是强制校验的，无法关闭 @zczhhhh
