### ISSUE TITLE
请问已经有或计划出 Flutter 相关SDK 么？

### ISSUE THREAD

**Issue by mny459** [qiniu/android-sdk#365]

**Comment by xushiwei** [comment]
已经在计划中

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-948

**Comment by YangSen-qn** [comment]
jira: KS-20

**Comment by bruce3x** [comment]
flutter 版 sdk 进度如何了呀？

**Comment by forrest-mao** [comment]
> flutter 版 sdk 进度如何了呀？

已经在开发中

**Comment by bachue** [comment]
@mny459 @bruce3x 已经发布 https://developer.qiniu.com/kodo/7598/flutter-sdk
