### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by DongDian455** [qiniu/android-sdk#367]
客户端的测试环境需连接代理，但是后台已经把七牛服务器上传部署到线上环境了，请问一下是否能配置测试环境跳过证书验证的呢？

**Comment by DongDian455** [comment]
代理用的是charles，已安装证书情况下有时候可以使用有时候不行

**Comment by JemyCheung** [comment]
如果是https的问题，您这边可以在Configuration配置useHttps(false) @DongDian455 
如果是其他问题您可以具体描述一下，我们看看

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-947
