### ISSUE TITLE
不可以上传第三方资源图片

### ISSUE THREAD

**Issue by minorlai** [qiniu/android-sdk#370]
我需要上传https://xxxxxxxx.jpg
结果：
{ver:7.5.0,ResponseInfo:1585672506853560,status:-6, reqId:, xlog:, xvia:, host:, path:, ip:, port:80, duration:0 s, time:1585673162, sent:0,error:file or data size is zero}

**Comment by JemyCheung** [comment]
上传文件需要的是buffer，或者文件路径
您可以先下载到本地，再上传。如果是服务端可以直接调用fetch接口抓取到七牛 @minorlai
