### ISSUE TITLE
7.6.0设置zone后，断点续传报错 incorrect region, please use up-z2.qiniup.com

### ISSUE THREAD

**Issue by g19980115** [qiniu/android-sdk#379]
Configuration.Builder().zone(FixedZone.zone2)，不设置zone就没事

**Comment by g19980115** [comment]
![image](https://user-images.githubusercontent.com/25760230/82435946-a1168b00-9ac7-11ea-805c-8c8211208de0.png)

**Comment by g19980115** [comment]
{ver:7.6.0,ResponseInfo:1589970399825902,status:400, xClientId:, reqId:fIgAAABvDc6ntRAW, xlog:X-Log, xvia:, host:upload-as0.qiniup.com, path:/, ip:14.119.114.97, port:443, duration:312 s, time:1589970400, sent:165443,error:incorrect region, please use up-z2.qiniup.com}

**Comment by JemyCheung** [comment]
我们处理一下 @g19980115

**Comment by JemyCheung** [comment]
更新到7.6.1再试试 @g19980115

**Comment by g19980115** [comment]
7.6.1可以了
