### ISSUE TITLE
DnsPrefetcher报ConcurrentModificationException 异常

### ISSUE THREAD

**Issue by fishflay** [qiniu/android-sdk#389]
java.util.ConcurrentModificationException

1 java.util.ArrayList$Itr.next(ArrayList.java:860)
2 com.qiniu.android.http.DnsPrefetcher.preHosts(DnsPrefetcher.java:8)
3 com.qiniu.android.http.DnsPrefetcher.init(DnsPrefetcher.java:3)
4 com.qiniu.android.http.DnsPrefetcher.startPrefetchDns(DnsPrefetcher.java:7)
5 com.qiniu.android.storage.UploadManager$4.run(UploadManager.java:1)
6 java.lang.Thread.run(Thread.java:929)

**Comment by JemyCheung** [comment]
哪个版本，必现吗
@fishflay

**Comment by fishflay** [comment]
版本是7.6.0   不是必现  不过出现次数挺多的

**Comment by JemyCheung** [comment]
更新到7.6.3版本 @fishflay
