### ISSUE TITLE
如何设置不走代理

### ISSUE THREAD

**Issue by cuibg** [qiniu/android-sdk#396]
可以设置不走代理吗？

**Comment by JemyCheung** [comment]
默认是不走代理的，您可以具体描述一下您所谓的代理是啥
@cuibg

**Comment by cuibg** [comment]
@JemyCheung 就是我进行抓包操作或者是其他的一些操作，能否绕过代理，现在一进行抓包就网络不通了

**Comment by cuibg** [comment]
https抓包的时候，上传图片就会失败

**Comment by cuibg** [comment]
还有一个就是同步上传比异步上传图片失败率要高的多得多！

**Comment by JemyCheung** [comment]
手机代理到电脑进行抓包？还是手机上直接抓包？
https抓包的时候上传是什么操作？
麻烦描述具体的场景，sdk内部是没有走任何代理的。

同步上传只针对小文件，建议都用异步上传 @cuibg

**Comment by cuibg** [comment]
手机代理到电脑上抓包

**Comment by cuibg** [comment]
@JemyCheung 我想的是用IntentService进行上传，如果用异步的话，就不好控制了

**Comment by cuibg** [comment]
还有一个就是，我如果用service上传图片之后，然后到最后在传给我们服务器的url，这样的话，用责任链感觉太麻烦了！！！！如果开启子线程同步上传，这样就不用控制先后操作了

**Comment by YangSen-qn** [comment]
1. 抓包问题：你可以查下失败的原因，是不是服务端配置的网关等有关。
2. 上传大文件建议使用异步分片上传，针对您的业务，我简单推荐一个方案，您可以参考下：
     1）第一步：资源上传至七牛，第二步：图片链接上传至你们的服务，把这两步封装成一个action，并对action状态做管理，保证每一个action的这两步是同步。
    2）当拥有多个action，多个action之间是异步，以此进行管理。
--- 仅供参考。

感谢您的反馈。

**Comment by cuibg** [comment]
@YangSen-qn 我们这儿是全部图片上传到7牛后，才将图片链接传到我们服务（同步上传经常会出现失败现象），防止多线程并发出现问题，用责任链感觉还靠谱点，感觉没有好的方式

**Comment by YangSen-qn** [comment]
@cuibg 你那边是保证所有图片上传到七牛都要成功，所以才采用同步上传吗？

**Comment by cuibg** [comment]
@YangSen-qn 是的，这样简单

**Comment by cuibg** [comment]
@YangSen-qn ，谢谢，还是采用的多线程并发上传

**Comment by YangSen-qn** [comment]
@cuibg 好的
