### ISSUE TITLE
是否支持图片压缩上传

### ISSUE THREAD

**Issue by cuibg** [qiniu/android-sdk#403]
服务端我了解到可以压缩图片，但是不知道Android的客户端有图片压缩上传么？

**Comment by JemyCheung** [comment]
您好，这边Android sdk没有压缩图片的功能，仅仅提供了上传
目前的Android端的图片压缩技术想要达到减小文件体积的目的的话，通常都是一种有损压缩，您可以百度一下android上压缩图片的方法，类似 https://blog.csdn.net/u013928412/article/details/80358597

然后处理的顺序就是
原始图片-->本地压缩-->利用七牛sdk进行上传 
感谢您的关注 @cuibg

**Comment by cuibg** [comment]
@JemyCheung 没有就知道了
