### ISSUE TITLE
DnsCacheFile每次都抛出IOException：mkdir failed

### ISSUE THREAD

**Issue by g19980115** [qiniu/android-sdk#408]
github的代码跟SDK内的不一样？

SDK 7.6.6这个地方有问题，`f.isDirectory()` 是始终返回 true 的，也就是说，即使文件夹存在也每次都会执行 `f.mkdirs();`

然后因为文件夹已存在，`mkdirs()`会返回false，

每次都抛出 IOExcetion
![微信截图_20200814173935](https://user-images.githubusercontent.com/25760230/90236348-3621e980-de55-11ea-8a82-4edb584ec977.png)

```Java
W/System.err: java.io.IOException: mkdir failed
W/System.err:     at com.qiniu.android.storage.persistent.DnsCacheFile.<init>(DnsCacheFile.java:26)
W/System.err:     at com.qiniu.android.http.DnsPrefetcher.startPrefetchDns(DnsPrefetcher.java:401)
W/System.err:     at com.qiniu.android.storage.UploadManager$4.run(UploadManager.java:235)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by forrest-mao** [comment]
内部跟进 issue：TS-1013

**Comment by YangSen-qn** [comment]
这个有写入权限吗

**Comment by g19980115** [comment]
有，且本地文件夹已存在

**Comment by g19980115** [comment]
你们github上的代码是正确的，SDK里面的判断反了
https://github.com/qiniu/android-sdk/blob/eaad26392e6d12c39bc1a02d3c5f000a68bb9c8a/library/src/main/java/com/qiniu/android/http/dns/DnsCacheFile.java#L21

**Comment by YangSen-qn** [comment]
好的

**Comment by Mei-Zhao** [comment]
新版本7.6.7修复了这个问题
