### ISSUE TITLE
上传图片报错时,回调进程的问题

### ISSUE THREAD

**Issue by ouyangyi01919** [qiniu/android-sdk#425]
上传图片是如果给一个目录的地址去上传,上传会报错,报错的回调发生在非UI线程,回调是在"OkHttp http:/upload-xs.qiniup.com/"线程
SDK 版本 7.3.15
复现步骤,上传时给一个目录的地址,必现

**Comment by YangSen-qn** [comment]
@ouyangyi01919  请更新最新版本SDK 8.0.3
