### ISSUE TITLE
8.0.0版本UploadSingleRequestMetrics.totalElapsedTime() on a null object reference

### ISSUE THREAD

**Issue by cuibg** [qiniu/android-sdk#428]
设备:vivo/FUNTOUCH
Android版本：Android 10,level 29
出错堆栈：

1 com.qiniu.android.http.metrics.UploadRegionRequestMetrics.totalElapsedTime(UploadRegionRequestMetrics.java:4)
--
2 com.qiniu.android.storage.PartsUpload.reportBlock(PartsUpload.java:12)
3 com.qiniu.android.storage.PartsUpload.completeAction(PartsUpload.java:1)
4 com.qiniu.android.storage.ConcurrentResumeUpload$1$1.complete(ConcurrentResumeUpload.java:4)
5 com.qiniu.android.storage.ConcurrentResumeUpload$5.complete(ConcurrentResumeUpload.java:3)
6 com.qiniu.android.http.request.RequestTransaction$10.complete(RequestTransaction.java:1)
7 com.qiniu.android.http.request.HttpRegionRequest.completeAction(HttpRegionRequest.java:1)
8 com.qiniu.android.http.request.HttpRegionRequest.access$400(HttpRegionRequest.java:1)
9 com.qiniu.android.http.request.HttpRegionRequest$1.complete(HttpRegionRequest.java:8)
10 com.qiniu.android.http.request.HttpSingleRequest.completeAction(HttpSingleRequest.java:4)
11 com.qiniu.android.http.request.HttpSingleRequest.access$700(HttpSingleRequest.java:1)
12 com.qiniu.android.http.request.HttpSingleRequest$3.complete(HttpSingleRequest.java:10)
13 com.qiniu.android.http.request.httpclient.SystemHttpClient.handleResponse(SystemHttpClient.java:19)
14 com.qiniu.android.http.request.httpclient.SystemHttpClient.access$300(SystemHttpClient.java:1)
15 com.qiniu.android.http.request.httpclient.SystemHttpClient$1.onResponse(SystemHttpClient.java:1)
16 okhttp3.RealCall$AsyncCall.run(RealCall.kt:7)
17 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
18 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
19 java.lang.Thread.run(Thread.java:919)

**Comment by YangSen-qn** [comment]
好的，感谢您的支持，我们尽快处理

**Comment by YangSen-qn** [comment]
内部跟进：KODO-10766

**Comment by YangSen-qn** [comment]
@cuibg 请更新最新版本SDK 8.0.3

**Comment by cuibg** [comment]
@YangSen-qn 好的

**Comment by cuibg** [comment]
@YangSen-qn 已经更新8.0.3版本了，但是还是存在这个问题
