### ISSUE TITLE
批量上传大量文件内存溢出，uploadManager为单例

### ISSUE THREAD

**Issue by werfei** [qiniu/android-sdk#433]
单文件平均3M多大小
看内存截图
![图片](https://user-images.githubusercontent.com/18606985/97799093-ad059c00-1c66-11eb-8fd3-5ba09045a1ca.png)

**Comment by YangSen-qn** [comment]
文件上传是采用分片的方式，所以上传会占用一定内存，其中非并发分片上传，单个文件需要4M的内存；并发上传时，根据并发上传的任务数量count计算，约为count * 4M。

建议：根据自身APP的情况，合理控制上传的任务数量。

**Comment by werfei** [comment]
非并发上传，上传任务数最大3个
![Uploading 图片.png…]()

**Comment by werfei** [comment]
内存占用是随着上传数量增长的，上传到一百多张的时候崩溃的，队列长度是五百多

**Comment by werfei** [comment]
看截图中的FormUpload 内存中的实例数是2，但是Request已经是150了

**Comment by werfei** [comment]
分析堆栈是
![图片](https://user-images.githubusercontent.com/18606985/97804329-0cc16e80-1c8a-11eb-9cc7-6202eec2f81e.png)
SystemHttpClient没有释放导致的
![Uploading 图片.png…]()
看这个对象里面的metrics属性responseInfo是有值的，这个请求已经完成了，但是内存一直没有释放，导致上传过多后未释放的内存太大就溢出了

**Comment by YangSen-qn** [comment]
@werfei 现在的SDK内部没有管理多个文件的上传操作，也就是UploadMananger每次调用upload function时，都会直接触发上传操作，当有多个文件同时触发上传时，SDK内部是会同时进行多个文件上传的，同时有过多的文件上传时会导致内存溢出的，所以app层需要管理同时上传的文件数量（比如同一时间，最多有n个文件上传，其余在排队，这些逻辑是需要APP层处理的，SDK暂时没有相关逻辑）。

**Comment by werfei** [comment]
这个已经处理了，同一时间最多有三个文件在上传

**Comment by werfei** [comment]
你看我dump出来的内存分析，SystemHttpClient这个对象一直没有释放

**Comment by YangSen-qn** [comment]
@werfei 你使用的SDK版本是多少？

**Comment by werfei** [comment]
最新版本

**Comment by YangSen-qn** [comment]
> 这个已经处理了，同一时间最多有三个文件在上传

方便看下你这个是怎么处理的吗？

**Comment by werfei** [comment]
我用了两种方案测试都有同样的问题。一种是使用workManager，然后限制线程池大小最大为3
![图片](https://user-images.githubusercontent.com/18606985/97822833-0ff04500-1cf2-11eb-92ab-d6b81bcd4b24.png)
另一种是我直接用线程池处理
![图片](https://user-images.githubusercontent.com/18606985/97822851-1e3e6100-1cf2-11eb-91b1-ab01d471b2bc.png)

**Comment by YangSen-qn** [comment]
> 我用了两种方案测试都有同样的问题。一种是使用workManager，然后限制线程池大小最大为3
> ![图片](https://user-images.githubusercontent.com/18606985/97822833-0ff04500-1cf2-11eb-92ab-d6b81bcd4b24.png)
> 另一种是我直接用线程池处理
> ![图片](https://user-images.githubusercontent.com/18606985/97822851-1e3e6100-1cf2-11eb-91b1-ab01d471b2bc.png)

因为上传是非阻塞式的，所以ExecutorService不能限制同时上传文件的数量，推荐以上传完成回调为信号，来判断一个文件是否正在上传中。

**Comment by werfei** [comment]
Wait wait = new Wait();
已经使用wait的方式等待上传结果返回
![图片](https://user-images.githubusercontent.com/18606985/97823296-7fb2ff80-1cf3-11eb-83d8-5a34e3b6c1ca.png)

**Comment by YangSen-qn** [comment]
@werfei 请再确认下SDK的版本，我这边测试，同一时刻上传4个文件，连续上传120个文件，内存平稳，在预期之内。

**Comment by YangSen-qn** [comment]
@werfei 请再确认下SDK的版本，我这边测试，同一时刻上传4个文件，每个文件大小3M，连续上传120个文件，内存平稳，在预期之内。

**Comment by werfei** [comment]
8.0.3
你上传五百个试试，您测试的这个120个文件上传完，内存占用大概多少

**Comment by YangSen-qn** [comment]
OPPO R9: 上传之前79M, 上传之后80M

**Comment by werfei** [comment]
您有邮箱或者什么吗？我把插件代码仓库发给您，帮忙看下原因吧，这个产品已经上线了

**Comment by werfei** [comment]
在我这的现象就是上传完的那些图片对应的byte数组没有释放，导致内存越来越大，Address和Request对象没有回收

**Comment by YangSen-qn** [comment]
yang_sen_ysys@163.com

**Comment by YangSen-qn** [comment]
> 您有邮箱或者什么吗？我把插件代码仓库发给您，帮忙看下原因吧，这个产品已经上线了

yang_sen_ysys@163.com

**Comment by YangSen-qn** [comment]
@werfei 加下你的微信？

**Comment by werfei** [comment]
wef7233

**Comment by werfei** [comment]
最新的8.0.3没有问题
