### ISSUE TITLE
上传图片出现server error

### ISSUE THREAD

**Issue by cuibg** [qiniu/android-sdk#444]
上传图片的时候会出现server error，退出应用，全部杀死应用后重启，有时候能够解决问题

**Comment by cuibg** [comment]
这个问题复现的步骤是，我在上传过程中断网，上传失败，然后连接网络，继续上传，就出问题了

**Comment by cuibg** [comment]
@lidaobing @why404 @bachue @xushiwei

**Comment by bachue** [comment]
@cuibg 请提供下 access key （无需提供 secret key） 和 sdk 版本号以及手机的型号，谢谢

**Comment by cuibg** [comment]
sdk是8.0.3，accesskey是？

**Comment by cuibg** [comment]
上传图片出现这个问题![image](https://user-images.githubusercontent.com/14813243/102685793-0ed19380-421e-11eb-9f30-d6331f528829.jpeg)![image](https://user-images.githubusercontent.com/14813243/102685794-1002c080-421e-11eb-9ceb-fc7ac148b7e6.jpeg)，是不是手机连接了代理就不行，Uploadmanager可不可以设置下不走手机代理，比如okhttp可以设置Proxy.No

**Comment by cuibg** [comment]
@bachue @lidaobing @why404 @longbai @BluntBlade

**Comment by YangSen-qn** [comment]
> 上传图片的时候会出现server error，退出应用，全部杀死应用后重启，有时候能够解决问题

请升级下SDK版本 8.0.5

**Comment by cuibg** [comment]
@YangSen-qn 这个failed connected 的问题呢，楼上的那个图片的问题

**Comment by YangSen-qn** [comment]
> @YangSen-qn 这个failed connected 的问题呢，楼上的那个图片的问题

代理是通过代码配置还是手机网络设置的

**Comment by cuibg** [comment]
@YangSen-qn 我想通过代码设置，不走任何代理，该如何操作？

**Comment by YangSen-qn** [comment]
> @YangSen-qn 我想通过代码设置，不走任何代理，该如何操作？

现在SDK暂不支持屏蔽系统代理，是什么原因想屏蔽系统代理呢？

**Comment by cuibg** [comment]
@YangSen-qn ![image](https://user-images.githubusercontent.com/14813243/102691136-499af200-4245-11eb-84b4-26e337a022da.jpeg)，出现这个问题的原因，是什么啊？这个原因我怀疑就跟https用fiddler抓包一样，会出问题，无法进行上传，因为我们也不知道用户连接的Wi-Fi有没有设置代理？这个问题如何解决啊？

**Comment by YangSen-qn** [comment]
> @YangSen-qn ![image](https://user-images.githubusercontent.com/14813243/102691136-499af200-4245-11eb-84b4-26e337a022da.jpeg)，出现这个问题的原因，是什么啊？这个原因我怀疑就跟https用fiddler抓包一样，会出问题，无法进行上传，因为我们也不知道用户连接的Wi-Fi有没有设置代理？这个问题如何解决啊？

用户上传操作是要确保网络正常的，如果通过手机设置了wifi代理，是需要保证代理网络正常的，这样上传才能成功；通过图片中提示，网络连接出现了问题，所以需要先确认下用户的代理网络是否正常。

**Comment by cuibg** [comment]
@YangSen-qn 好的谢谢
