### ISSUE TITLE
上传图片

### ISSUE THREAD

**Issue by cuibg** [qiniu/android-sdk#445]
1. 上传的responsetime，是整个文件上传完成的时间吗？
2. 可以自己写上传不用七牛的sdk吗？
@lidaobing @why404 @bachue @xushiwei @hughlv @hughlv @longbai

**Comment by YangSen-qn** [comment]
1. 是ResponseInfo 中的 timeStamp？
2. 可以的，具体见下述文档：
>  表单：https://developer.qiniu.com/kodo/api/1312/upload
> 分片V1: https://developer.qiniu.com/kodo/api/7443/shard-to-upload

**Comment by cuibg** [comment]
是响应时间，这个时间

**Comment by cuibg** [comment]
在uploadmanger中设置的，响应时间，怎么理解，是整个上传的时间嘛？

**Comment by YangSen-qn** [comment]
> 是响应时间，这个时间

是Configuration中的responseTimeout？

**Comment by cuibg** [comment]
对的，这个时间是上传的总时间吗

**Comment by cuibg** [comment]
@YangSen-qn Configuration中connectTimeout 这个时间和responseTimeout这个时间一个是连接的总时间，一个是从连接到响应的时间？

**Comment by YangSen-qn** [comment]
> 对的，这个时间是上传的总时间吗

这个responseTimeout是7版本遗留，在8版本上传流程中已经废弃，但其他流程还在使用，直接使用connectTimeout就可以了，connectTimeout对应到OKHttp中的connectTimeout和readTimeout

**Comment by cuibg** [comment]
@YangSen-qn 你们那里没有做过统计，这个connnecttime设置多少事最适的？

**Comment by YangSen-qn** [comment]
> @YangSen-qn 你们那里没有做过统计，这个connnecttime设置多少事最适的？

默认值就是现阶段最优的，如果后面统计需要调整的话会调整默认值
