### ISSUE TITLE
Android10无法上传图库的文件

### ISSUE THREAD

**Issue by moviesguo** [qiniu/android-sdk#450]
SDK版本 : 8.1.1
Android版本 ： 29

上传图片时提示 get upload file data error 
有没有考虑提供uri的上传方式

**Comment by jiqiuyu** [comment]
{ver:8.1.1,ResponseInfo:1610698681712915,status:-6, reqId:, xlog:null, xvia:null, host:null, time:1610698749,error:file is empty}
同Android 10.0 无法上传

**Comment by bachue** [comment]
@jiqiuyu 看错误信息，这个是空文件吧？

**Comment by YangSen-qn** [comment]
@moviesguo @jiqiuyu 如果文件是通过filePath指定，需要确保filePath中的文件有效且不为空，并且使用new File(filePath)可以获取到文件信息，以及使用RandomAccessFile可以读取到文件内容。

**Comment by YangSen-qn** [comment]
> SDK版本 : 8.1.1
> Android版本 ： 29
> 
> 上传图片时提示 get upload file data error
> 有没有考虑提供uri的上传方式

可以直接传入File对象，需要确保File有效且文件内容不为空
```
/**
     * 上传文件
     *
     * @param file     上传的文件对象
     * @param key      上传文件保存的文件名
     * @param token    上传凭证
     * @param completionHandler 上传完成的后续处理动作
     * @param options  上传数据的可选参数
     */
    public void put(final File file,
                              final String key,
                              final String token,
                              final UpCompletionHandler completionHandler,
                              final UploadOptions options)
```

**Comment by jiqiuyu** [comment]
确认了，不是qiniu的问题。感谢~
