### ISSUE TITLE
关于Android10 上传文件适配问题

### ISSUE THREAD

**Issue by weihuihuang** [qiniu/android-sdk#451]
最近在视频Android10,从相册选取视频，得到的路径无法直接通过put(String filePath, String key, String token,UpCompletionHandler completionHandler,final UploadOptions options) 进行上传，因为没有访问权限。改用 put(final byte[] data, final String key, final String token,final UpCompletionHandler complete, final UploadOptions options)读取字节流的话，视频太大会OOM，请问有没有好的解决办法。

**Comment by bachue** [comment]
```
public void put(final File file,
                    final String key,
                    final String token,
                    final UpCompletionHandler completionHandler,
                    final UploadOptions options)
```

[UploadManager](https://github.com/qiniu/android-sdk/blob/master/library/src/main/java/com/qiniu/android/storage/UploadManager.java#L100) 的这个接口能不能用呢？

**Comment by weihuihuang** [comment]
> @weihuihuang
> 
> ```
> public void put(final File file,
>                     final String key,
>                     final String token,
>                     final UpCompletionHandler completionHandler,
>                     final UploadOptions options)
> ```
> 
> [UploadManager](https://github.com/qiniu/android-sdk/blob/master/library/src/main/java/com/qiniu/android/storage/UploadManager.java#L100) 的这个接口能不能用呢？

您好，您说的接口其实和上面的通过path调用上传的接口本质是一样的，源码里面只是通过new File(filePath)调用了这个接口。
Android10打开了分区存储之后限制了app外部专属目录和私有目录以外的文件通过File直接进行操作，只能通过Uri进行操作。
我是因为这种情况获取到了相册视频的Uri,通过Uri获取字节数组，上传才出现了问题。上传图片倒是挺顺利，视频就不行了，上传了一个500M的视频getByteDataByContentUri就会OOM了，Android10以下用你们常规的path传递你们做了分片上传处理才正常。
![image](https://user-images.githubusercontent.com/27261747/105490811-4f766e00-5cf0-11eb-8ef2-d22993d7c1f0.png)

**Comment by YangSen-qn** [comment]
@weihuihuang 可以尝试把Uri转换成URL

**Comment by weihuihuang** [comment]
> @weihuihuang 可以尝试把Uri转换成URL

您好，有空的时候，能稍微具体说下么，没查到您说的，我只知道Android这边的Uri和真实path之间的互转。

**Comment by YangSen-qn** [comment]
> > @weihuihuang 可以尝试把Uri转换成URL
> 
> 您好，有空的时候，能稍微具体说下么，没查到您说的，我只知道Android这边的Uri和真实path之间的互转。

对的，就是Uri和真实path之间的互转

**Comment by weihuihuang** [comment]
> > > @weihuihuang 可以尝试把Uri转换成URL
> > 
> > 
> > 您好，有空的时候，能稍微具体说下么，没查到您说的，我只知道Android这边的Uri和真实path之间的互转。
> 
> 对的，就是Uri和真实path之间的互转

哦哦，我最开始的问题就是，真实path适配分区存储之后没有File操作权限。。

**Comment by YangSen-qn** [comment]
@weihuihuang 你GitHub上有demo吗，我大概看下？

**Comment by weihuihuang** [comment]
> @weihuihuang 你GitHub上有demo吗，我大概看下？

没有，是我们这边的业务代码,最近做适配。我本来想下载你们的https://github.com/clouddxy/AndroidDemo 看看的，发现很久没更新了。。

**Comment by YangSen-qn** [comment]
@weihuihuang 你使用使用这个Demo试试？
 https://github.com/YangSen-qn/UploadDemo_Android

**Comment by weihuihuang** [comment]
> @weihuihuang 你使用使用这个Demo试试？
> https://github.com/YangSen-qn/UploadDemo_Android

![image](https://user-images.githubusercontent.com/27261747/105794647-5d651100-5fc6-11eb-825b-954370640ab3.png)
你这个token我好像随便配一个UUID不行。

**Comment by YangSen-qn** [comment]
@weihuihuang 这个token是七牛的上传上传凭证（https://developer.qiniu.com/kodo/1208/upload-token），应该是从你们服务获取，不是UUID.

**Comment by weihuihuang** [comment]
> @weihuihuang 这个token是七牛的上传上传凭证（[https://developer.qiniu.com/kodo/1208/upload-token），应该是从你们服务获取，不是UUID](https://developer.qiniu.com/kodo/1208/upload-token%EF%BC%89%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%98%AF%E4%BB%8E%E4%BD%A0%E4%BB%AC%E6%9C%8D%E5%8A%A1%E8%8E%B7%E5%8F%96%EF%BC%8C%E4%B8%8D%E6%98%AFUUID).
哦哦我随便从我们服务端哪一个就行了么，但是requestLegacyExternalStorage关掉之后这个问题你们有关注么。

**Comment by weihuihuang** [comment]
> > @weihuihuang 这个token是七牛的上传上传凭证（[https://developer.qiniu.com/kodo/1208/upload-token），应该是从你们服务获取，不是UUID](https://developer.qiniu.com/kodo/1208/upload-token%EF%BC%89%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%98%AF%E4%BB%8E%E4%BD%A0%E4%BB%AC%E6%9C%8D%E5%8A%A1%E8%8E%B7%E5%8F%96%EF%BC%8C%E4%B8%8D%E6%98%AFUUID).

哦哦我随便从我们服务端哪一个就行了么，但是requestLegacyExternalStorage关掉之后这个问题你们有关注么。

**Comment by YangSen-qn** [comment]
> > > @weihuihuang 这个token是七牛的上传上传凭证（[https://developer.qiniu.com/kodo/1208/upload-token），应该是从你们服务获取，不是UUID](https://developer.qiniu.com/kodo/1208/upload-token%EF%BC%89%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%98%AF%E4%BB%8E%E4%BD%A0%E4%BB%AC%E6%9C%8D%E5%8A%A1%E8%8E%B7%E5%8F%96%EF%BC%8C%E4%B8%8D%E6%98%AFUUID).
> 
> 哦哦我随便从我们服务端哪一个就行了么，但是requestLegacyExternalStorage关掉之后这个问题你们有关注么。

你那边是出于什么方面原因 要关掉这个开关呢？

**Comment by weihuihuang** [comment]
> > > > @weihuihuang 这个token是七牛的上传上传凭证（[https://developer.qiniu.com/kodo/1208/upload-token），应该是从你们服务获取，不是UUID](https://developer.qiniu.com/kodo/1208/upload-token%EF%BC%89%EF%BC%8C%E5%BA%94%E8%AF%A5%E6%98%AF%E4%BB%8E%E4%BD%A0%E4%BB%AC%E6%9C%8D%E5%8A%A1%E8%8E%B7%E5%8F%96%EF%BC%8C%E4%B8%8D%E6%98%AFUUID).
> > 
> > 
> > 哦哦我随便从我们服务端哪一个就行了么，但是requestLegacyExternalStorage关掉之后这个问题你们有关注么。
> 
> 你那边是出于什么方面原因 要关掉这个开关呢？

我们项目升级targetSdk到了29，在Android 版本 1的手机上app卸载重装的话这个开关就没用了吧。

**Comment by YangSen-qn** [comment]
@weihuihuang 如果requestLegacyExternalStorage设置为true，对你们的APP有什么影响吗？Android 11可以使用File，没有什么影响。

**Comment by weihuihuang** [comment]
> @weihuihuang 如果requestLegacyExternalStorage设置为true，对你们的APP有什么影响吗？Android 11可以使用File，没有什么影响。

这个倒是没啥影响。对，我知道，11上面公共目录的媒体文件又可以直接操作File了。。无语。。我先问下我们这边怎么说吧。
