### ISSUE TITLE
七牛上传返回得错误，经常出现

### ISSUE THREAD

**Issue by cuibg** [qiniu/android-sdk#452]
{ver:8.1.0,ResponseInfo:161155521069425,status:-6, reqId:, xlog:null, xvia:null, host:null, time:1611555245,error:file is empty}，文件是存在的

**Comment by YangSen-qn** [comment]
@cuibg 检查下是否有权限，以及文件路径是否正确，需要保证文件能够读出，Android 10 需要将URI转化为绝对path。

**Comment by cuibg** [comment]
已经检查，没有问题，文件是没有问题的，Android10下也是绝对得path

**Comment by cuibg** [comment]
@YangSen-qn 而且上面返回得host是null，这个该怎么理解啊

**Comment by YangSen-qn** [comment]
> @YangSen-qn 而且上面返回得host是null，这个该怎么理解啊

-6 是文件检查异常，还没有到网络请求流程

**Comment by cuibg** [comment]
@YangSen-qn 好的

**Comment by cuibg** [comment]
![image](https://user-images.githubusercontent.com/14813243/105794222-833de600-5fc5-11eb-92f6-b3a8a31c03b4.png)
不应该会判断文件是null得
