### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by gryllsi** [qiniu/android-sdk#454]
错误信息：{ver:7.4.6,ResponseInfo:1613874123083696,status:-1, xClientId:, reqId:, xlog:, xvia:, host:upload-xs.qiniup.com, path:/, ip:, port:80, duration:-1 s, time:1613874126, sent:-1,error:Connection reset}

之前开启https有的机型会出现（useHttps(true)），关闭后可以上传，现在还是会出现这种错误，有什么解决方案么？

**Comment by YangSen-qn** [comment]
@gryllsi 可以尝试升级 SDK 到最新版本
