### ISSUE TITLE
啥时候支持Uri上传? 复制文件的做法太挫了

### ISSUE THREAD

**Issue by chenqi777** [qiniu/android-sdk#457]
>在 Android 11 上运行但以 Android 10（API 级别 29）为目标平台的应用仍可请求 requestLegacyExternalStorage 属性。应用可以利用此标记暂时停用与分区存储相关的变更，例如授予对不同目录和不同类型的媒体文件的访问权限。当您将应用更新为以 Android 11 为目标平台后，系统会忽略 requestLegacyExternalStorage 标记。

target sdk为Android 11无法无法访问外部存储目录, 并且Google下半年会禁止Android 11以下的APP上架和更新, 复制小文件再上传倒无所谓, 大文件就不太合适了.

**Comment by YangSen-qn** [comment]
@chenqi777 已在计划中

**Comment by YangSen-qn** [comment]
v8.3.0 开始支持 Uri, 请升级 SDK 版本
