### ISSUE TITLE
错误信息是applicaiton/octet-stream

### ISSUE THREAD

**Issue by cuibg** [qiniu/android-sdk#458]
{ver:8.1.0,ResponseInfo:1618904298482660,status:403, reqId:-UwAAAAimrkwgXcW, xlog:X-Log, xvia:null, host:upload.qiniup.com, time:1618904636,error:limited mimeType: this file type (application/octet-stream) is forbidden to upload},传的文件是图片

**Comment by YangSen-qn** [comment]
> {ver:8.1.0,ResponseInfo:1618904298482660,status:403, reqId:-UwAAAAimrkwgXcW, xlog:X-Log, xvia:null, host:upload.qiniup.com, time:1618904636,error:limited mimeType: this file type (application/octet-stream) is forbidden to upload},传的文件是图片

https://developer.qiniu.com/kodo/1206/put-policy,  token 里面 policy 中的 mimeLimit参数看一下，是否做了限制
