### ISSUE TITLE
8.2.0及以后的新版本 syncPut之后无返回

### ISSUE THREAD

**Issue by 932707629** [qiniu/android-sdk#460]
刚开始用的8.3.0版本  发现syncPut之后一直在wait 没有收到ResponseInfo的返回 以为是自己的代码的问题  经反复确认后发现是sdk版本问题  8.2.0(8.2.0、8.2.1、8.3.0)以后的版本都是收不到ResponseInfo返回的  老版本8.1.2(测试了8.1.2和8.0.5)可以收到

**Comment by YangSen-qn** [comment]
@932707629  你那边是在主线程调用的吗？

**Comment by 932707629** [comment]
> @932707629 你那边是在主线程调用的吗？

不是 同步都是在子线程调用的

**Comment by YangSen-qn** [comment]
用的是哪个方法呢？

**Comment by 932707629** [comment]
> @932707629 用的是哪个方法呢？我们这边验证没有复现这个问题

您好这边用的demo验证的  代码如下
`
        AsyncTask.execute(new Runnable() {
            @Override
            public void run() {
                ResponseInfo respInfo=uploadManager.syncPut(uploadFile,keyname,uploadToken,opt);
                long endTime = System.currentTimeMillis();
                if (respInfo.isOK()) {
                    try {
                        Log.e("zw", respInfo.response.toString() + respInfo.toString());
                        writeLog("--------------------------------UPTime/ms: " + (endTime - startTime));
                        String fileKey = respInfo.response.getString("key");
                        String fileHash = respInfo.response.getString("hash");
                        writeLog("File Size: " + Tools.formatSize(uploadFileLength));
                        writeLog("File Key: " + fileKey);
                        writeLog("File Hash: " + fileHash);
                        writeLog("X-Reqid: " + respInfo.reqId);
                        writeLog("X-Via: " + respInfo.xvia);
                        writeLog("--------------------------------" + "\n上传成功");
                    } catch (JSONException e) {
                        writeLog(MainActivity.this
                                .getString(com.qiniu.jemy.upload.R.string.qiniu_upload_file_response_parse_error));
                        if (respInfo.response != null) {
                            writeLog(respInfo.response.toString());
                        }
                        writeLog("--------------------------------" + "\n上传失败");
                    }
                } else {
                    writeLog(respInfo.toString());
                    if (respInfo.response != null) {
                        writeLog(respInfo.response.toString());
                    }
                    writeLog("--------------------------------" + "\n上传失败");
                }
            }
        });
`

**Comment by 932707629** [comment]
看了下issue  是跟okhttp版本有关系吗 我的版本也是4.9.1

**Comment by YangSen-qn** [comment]
> 看了下issue 是跟okhttp版本有关系吗 我的版本也是4.9.1

使用 okhttp 4.2.2试试，okhttp 4.9.1 现在有些问题，后面会处理

**Comment by 932707629** [comment]
好像跟okhttp关系不大  demo用的是8.3.0依赖的okhttp版本  看了下依赖树 是用的okhttp4.2.2  还是一样syncPut之后没有返回ResponseInfo 一直在等待  测试代码:https://github.com/932707629/upload_android-master

**Comment by YangSen-qn** [comment]
> 好像跟okhttp关系不大 demo用的是8.3.0依赖的okhttp版本 看了下依赖树 是用的okhttp4.2.2 还是一样syncPut之后没有返回ResponseInfo 一直在等待 测试代码:https://github.com/932707629/upload_android-master

需要增加权限，请核对下：
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
