### ISSUE TITLE
HttpDns类中找不到 com/qiniu/android/dns/http/DnspodFree;

### ISSUE THREAD

**Issue by pengchao1989** [qiniu/android-sdk#471]
如题，最近两三个版本运行时崩溃

**Comment by YangSen-qn** [comment]
请确认以下几个问题：
1. qiniu android-sdk 版本号
2. 依赖的 HappyDns 版本号
3. 是否必现

**Comment by pengchao1989** [comment]
@YangSen-qn 
qiniu android-sdk   8.3.1
happy-dns  1.0.0
必现


我run的时候提示DnspodFree这个类找不到

public class HttpDns implements Dns {

    private IResolver httpResolver;

    public HttpDns(int timeout) {
        httpResolver = new DnspodFree("119.29.29.29", timeout);
    }

**Comment by YangSen-qn** [comment]
@pengchao1989 正常情况， 8.3.1 依赖的 SDK  HappyDns  0.2.18 而不是 1.0.0。

**Comment by pengchao1989** [comment]
找不到的这个 DnspodFree 类是 qiniu的包里的啊


package com.qiniu.android.http.dns;

import com.qiniu.android.dns.Domain;
import com.qiniu.android.dns.IResolver;
import com.qiniu.android.dns.Record;
**import com.qiniu.android.dns.http.DnspodFree;**

import java.io.IOException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HttpDns implements Dns {

    private IResolver httpResolver;

    public HttpDns(int timeout) {
        **httpResolver = new DnspodFree("119.29.29.29", timeout);**
    }

**Comment by YangSen-qn** [comment]
@pengchao1989  SDK v8.3.1 应该是依赖 HappyDns 版本是 v0.2.18, 你那边是不是直接或者间接修改了依赖的版本？

**Comment by xulonc** [comment]
可参考下这里
```
implementation ('com.qiniu:happy-dns'){
        version{
            strictly('0.2.18') // 如果觉得1.0版本不行，这里强制改为依赖0.2.18版本
        }
    }
implementation group: 'com.qiniu', name: 'qiniu-android-sdk', version: '8.4.1'  // 这里默认会自动依赖haapy-dns 1.0版本
```
