### ISSUE TITLE
七牛云从8.3.0版本之后就没有进度

### ISSUE THREAD

**Issue by billdizl** [qiniu/android-sdk#477]
七牛云v8.3.0 没有进度无法获得上传成功回调
v8.3.0之后的版本 只有上传成功进度为1.0,没有正在上传的进度展示

**Comment by YangSen-qn** [comment]
> 七牛云v8.3.0 没有进度无法获得上传成功回调 v8.3.0之后的版本 只有上传成功进度为1.0,没有正在上传的进度展示

测试 v8.3.3 正常回调；请注意回调线程为主线程，不需要在回调中切主线程

**Comment by billdizl** [comment]
经测试 可能我之前测试的上传的图片较小 所以更新进度没有展示出来,直接变为了1, 七牛云v8.3.0版本确实存在无更新进度的问题,其余版本经测试都是正常的
