### ISSUE TITLE
503 上传者错误

### ISSUE THREAD

**Issue by nizhege** [qiniu/android-sdk#486]
有遇到过这个错误么

**Comment by bachue** [comment]
@nizhege 能截个图看看吗？

**Comment by nizhege** [comment]
> 

![image](https://user-images.githubusercontent.com/17634817/175221965-887b6954-3977-44cf-8c30-250da8ae5086.png)

**Comment by bachue** [comment]
@nizhege 我看到你的 upload token 里是有 callbackUrl 的，这个错误可能来自于这个 callbackUrl，因为在七牛，对于有 callbackUrl 的情况，是直接返回这个 callback 的 response 的。

**Comment by nizhege** [comment]
> 

没太懂你说的什么意思 可以详细点吗

**Comment by nizhege** [comment]
> @nizhege 可以看下 https://developer.qiniu.com/kodo/1653/callback ，七牛对于回调的响应是透传的，所以 503 上传者错误 应该是来自于回调服务器的响应

主要是前几天都没有问题，从昨天开始报的错 代码都没动

**Comment by nizhege** [comment]
> @nizhege 可以看下 https://developer.qiniu.com/kodo/1653/callback ，七牛对于回调的响应是透传的，所以 503 上传者错误 应该是来自于回调服务器的响应

问题找到了 感谢回复
