### ISSUE TITLE
上传图片进行转码

### ISSUE THREAD

**Issue by CNRZWP** [qiniu/android-sdk#497]
请问上传图片时如何修改保存的图片类型？例如上传jpeg时统一保存为png图片。试了下UploadOptions中配置mimeType是无效的

**Comment by bachue** [comment]
设置 mimeType 指的是配置上传的文件的 MIME 类型，文件内容不会改变。你的需求需要使用 PFOP 来转码，在 JPEG 文件上传后，用 FOP 将文件异步转码成 PNG 再重新写回云存储，可以参考 https://developer.qiniu.com/kodo/1206/put-policy#persistentOps 来设置 FOP 命令，然后 FOP 命令的写法参考文档 https://developer.qiniu.com/dora/1279/basic-processing-images-imageview2
