### ISSUE TITLE
Android11以上公共存储目录里面的非媒体类文件上传会报permission denied错误

### ISSUE THREAD

**Issue by Ryokooo** [qiniu/android-sdk#514]
非媒体类文件上传失败提示为没有权限, 但是实际上应用是能访问这些文件的不会出现权限报错的问题, 到了上传这一步后就会报权限错误, 需要申请manage_external_storage, 但是其他的应用如微信 飞书等并不需要申请这个权限也能发送非媒体类的文件, 这是什么原因呢?

**Comment by YangSen-qn** [comment]
考虑到并非所有 APP 均需要 MANAGE_EXTERNAL_STORAGE 这个权限，为了不过多声明权限，所以七牛 SDK 内部并没有声明这个权限；

当使用七牛 SDK 进行上传时需要自己检测上传内容是否有权限访问，当确认有权限访问时再进行上传。
