### ISSUE TITLE
疑似bug反馈

### ISSUE THREAD

**Issue by mybuddy** [qiniu/android-sdk#95]
sdk中对于分片上传的片大小配置，如果片大小不能够整除块大小的话（即 BLOCK_SIZE % CHUNK_SIZE != 0），可能会出现read exceed block size的错误。
引起该问题的代码为
/library/src/main/java/com/qiniu/android/storage/ResumeUploader.java 中的

private int calcPutSize(int offset) {
        int left = size - offset;
        return left < Config.CHUNK_SIZE ? left : Config.CHUNK_SIZE;
}
如果配置中BLOCK_SIZE % CHUNK_SIZE != 0的话，每块的最后一片大小也需要考虑，而不仅仅是整个文件的最后一片大小。

不知是否是个bug

**Comment by longbai** [comment]
@mybuddy ，谢谢提醒，这个没有考虑过。我们推荐片大小都是要整除块大小的。
